### ISSUE TITLE
Tapping the bang button dismisses the popover showing search suggestions on the iPad

### ISSUE THREAD

**Issue by mark5422** [duckduckgo/ios-search-and-stories#101]
After tapping to search on the iPad, tapping the bang button dismisses the search suggestion list that changes as you type (the one in the attached image).

![screen shot 2015-09-21 at 23 43 59](https://cloud.githubusercontent.com/assets/641358/10007166/0382b63e-60bb-11e5-93b1-3683f76981b9.png)

**Comment by sreilly** [comment]
fixed in code; waiting on testflight.

**Comment by thm** [comment]
Marking complete as this looks fixed to me. Thanks Sean, and Mark for spotting the issue!
