### ISSUE TITLE
Wrong title in empty-state

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#103]
@sreilly The empty-state on the **Favorite Stories** page says "**No Recents**", can you please confirm for all empty states that we're using the correct title and description?

**Comment by thm** [comment]
@sreilly Also, for the empty-state on the "Recent Stories" page we're showing a heart-icon rather than the clock-icon (it's correct on the "Recent Searches" page). In addition, the line-height for descriptions doesn't seem to be consistent. Switch between the Recents pages and you'll notice it immediately

**Comment by thm** [comment]
@sreilly In the changelog you mentioned this was fixed. However, I'm unable to confirm this as the "Clear Recents" option crashes the app

**Comment by sreilly** [comment]
@thm Yes, that should be another bug ticket... I'll try and knock that one out tomorrow!

**Comment by sreilly** [comment]
@thm the clear-recents bug is now fixed in the current hockey build.  Can you try it out and see if we can close this one?
