### ISSUE TITLE
More popups to be removed

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#104]
1. When clearing recents from Settings
2. When you favorite a search from the search tabbar

@sreilly please remove all black popups completely, everywhere

**Comment by sreilly** [comment]
This is done and committed but waiting for testflight

**Comment by thm** [comment]
Small detail, can you make the "Clear Recents" option on the Settings page grey out when there are no recents left to clear? After clearing the recents this would be a nice confirmation. The grey color to be used would be the same as the list item's secondary titles (ie. "Stories (Default)" for the homepage setting)

**Comment by sreilly** [comment]
@thm done in the current hockey build

**Comment by thm** [comment]
@sreilly perfect
