### ISSUE TITLE
Added functionality for back button

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#106]
In the Search view, when you're on the first page, the left-pointing arrow in the tabbar has no functionality. Can you give it the same functionality as the home icon at the top-left? So, when on the first page in Search make the previous-arrow return to Stories like the home-button does.

**Comment by sreilly** [comment]
fixed in git!  waiting for testflight to catch up (it's over 24 hours behind now... so I'm on the phone with Apple)
