### ISSUE TITLE
Tapping outside story-menu should dismiss it

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#107]
@sreilly When tapping outside of the story-menu (the three-dot menu) can you make sure it only dismisses the menu rather than dismissing it and going to the story you just clicked? All other functionality should remain. So, scrolling while the menu is open should dismiss it and initiate a scroll as expected.

**Comment by SwiftlyDeft** [comment]
This has been fixed, will be able to test in this week's beta build

**Comment by thm** [comment]
@SwiftlyDeft if I initiate a scroll while the story-menu is open, then the scroll is disregarded while the menu is being closed. After the menu is closed I have to scroll again to actually scroll the page. Is there an easy way around this? can we catch the scroll-gesture and scroll the page in tandem with the menu closing?

**Comment by SwiftlyDeft** [comment]
@thm, This is been updated, and now works as expected. Tapping on the cell when the menu is open will dismiss the menu. Scrolling the page will dismiss the menu. Tapping on another cell will hide the menu and go into the story of the cell. Thanks!

**Comment by thm** [comment]
@SwiftlyDeft thanks, this is much better. However, I don't think it's very user-friendly to scroll the page (or not) based on the cell/story on which you initiate the scroll. It feels very inconsistent if the page scrolls only sometimes, and in some cases only closes the menu. As outlined in my previous comment I think we should aim to close the menu regardless of where you initiate the scroll. If this is not technically possible or very time-consuming to implement, then please let me know and we can find an alternative, or we could leave it be and revert back to only closing the menu.

**Comment by thm** [comment]
@SwiftlyDeft I've tested this in the latest build (v743) and you may still be working on it, but it's really close. I only noticed that the "Add to Favorites" link doesn't work the first time and you have to either tap it again to see it update or reopen the menu to update it. We should probably close the menu when the story is added to favorites anyway.

**Comment by sreilly** [comment]
If we close the menu upon add/remove favourite then should we also restore the popup/toast indicator?

**Comment by SwiftlyDeft** [comment]
@thm Have a play with the latest build. Especially around the whole Add/Remove part. Let me know if it suits and if there's are anything that can be improved on in this area.

**Comment by SwiftlyDeft** [comment]
@thm: I'll let you know once a build has been prepared fixing a few other issues at the moment. Be ready soon! Thanks

**Comment by SwiftlyDeft** [comment]
@thm This is all ready for you to try out now.
