### ISSUE TITLE
Story feed resets after sharing

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#108]
@sreilly here's how to reproduce the issue:
1. Scroll down several articles so that the view is decently far from the top article
2. Tap three-dot button and “Share”
3. Tap email and then I tap “cancel” to close the email and delete the draft
4. RESULT: The scroll position is now all the way back to the top and the feed is refreshed

**Comment by SwiftlyDeft** [comment]
Does not seem to be an issue anymore, please have a check in this weeks beta build. Thanks Josiah Clumont

**Comment by thm** [comment]
@SwiftlyDeft awesome, marking complete!
