### ISSUE TITLE
all stories not coming through 

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#11]
noticed that I am not seeing all the sources represented by the server on the client

**Comment by nilnilnil** [comment]
@yegg @theinfinitekind

**Comment by ghost** [comment]
@nilnilnil 

Are you able to provide some details of the ones that are missing?

**Comment by yegg** [comment]
For example I never see NPR despite it being default and marked on for me.

**Comment by ghost** [comment]
@yegg 

Are you using the live version from the App Store, or the current TF build?

**Comment by yegg** [comment]
Store

**Comment by ghost** [comment]
@yegg 

Hmmm. I've a feeling this one might be a tough nut to crack.

I've just downloaded the version from the App Store, and the 4th item in the stories feed is an article from NPR.

![screenshot 2014 03 05 13 33 22](https://f.cloud.github.com/assets/20023/2333415/df400dca-a46a-11e3-8078-e97f05febc6b.png)

I can't see why you or @nilnilnil wouldn't be seeing some articles, unless either the app has got itself into some unusual state, or something's corrupt.

**Comment by quanganhdo** [comment]
Same here as well. Store version shows the NPR story for me.

**Comment by yegg** [comment]
It's really per story not source. Look at the watrcoolr output for the default and compare to the stories in the app 1 by 1. Apparently random ones are missing.

**Comment by ghost** [comment]
@nilnilnil @yegg 

Is **Settings > Readability > Only show articles with Readability** checked?

If so, try unchecking it and then navigating back to the story feed.

Are missing articles now showing?

**Comment by yegg** [comment]
That's it! I think we should consider changing the default on that. The % coverage is not good.

**Comment by nilnilnil** [comment]
I thought I was still seeing them with it only on when available, but I just confirmed that they are all there in the feed.  So silly :/.  Anyways thanks!  I agree with @yegg, we need to make on when available the default here.

**Comment by sreilly** [comment]
I'd like to vote for completely removing the option to hide articles that don't have readability support.

It seems odd to hide certain stories for reasons that are non-deterministic as far as the user is concerned.  With the option on, stories are hidden for reasons having nothing to do with the quality of the story.... that just seems wrong to me.  Of course I'm happy with simply changing the default too.
