### ISSUE TITLE
Bangs-related text appears at bottom of screen

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#116]
How to reproduce:
1. Tap search-field
2. Tap bangs icon, then tap "Cancel"
3. RESULT: text appears at bottom of screen

![photo 24-09-15 5 13 43 pm](https://cloud.githubusercontent.com/assets/1379822/10077238/ce89cdc4-62df-11e5-8194-2590abb661e1.png)

**Comment by sreilly** [comment]
fixed!
