### ISSUE TITLE
New search-field issues

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#118]
1. After searching, the query that replaces the placeholder often overlays the placeholder and animates in from the top left of the search-field. It makes it look really buggy. It seems to happen once, after a cold start.
2. After a search, the search-field really slowly animates when taking up the space of the "Cancel" button

**Comment by sreilly** [comment]
This should be fixed in the current testflight build (652)

**Comment by thm** [comment]
I'm still seeing the first issue mentioned above, the second one is fixed thanks

**Comment by sreilly** [comment]
@thm the first issue is now fixed and will be in the next build!

**Comment by thm** [comment]
From a cold start, the search-field's placeholder is now aligned to the left without the search-icon. (rather than being centered, with the search-icon). Other than that, the issues above seem to be solved!

**Comment by sreilly** [comment]
@thm I'm not sure I understand, although I've rewritten the placeholder code in order to avoid all of the weirdness that was coming from the built-in text field placeholder.  The placeholder behaviour is now completely under our control so any misbehaving should be easily resolvable.  Can you check out the current hockey build and let me know if it doesn't address this?

**Comment by thm** [comment]
@sreilly yes, this issue is solved now! A new issue I'm seeing is that from a cold start the placeholder moves from the right to the left when switching between tabs (maybe only 10-20 pixels), and then after that it works fine for each tab.

**Comment by sreilly** [comment]
@thm are you still seeing this?  I can't detect any movement in the placeholder when switching tabs.  If you are still seeing it, could you post a video of it happening?

**Comment by thm** [comment]
@sreilly sure, [here's a demo](http://cl.ly/0d002H3y2w0k/demo.mp4). Look at the search-field when switching pages. Then when going back, visiting each page a second time shows the placeholder remaining still, as expected.

Another bug you can see here is the shifted Stories feed. At first you see the 'Jessica Simpson' story, and then later when visiting the Stories page for a second time it's 'Harry Potter' all of a sudden. Magic?

**Comment by sreilly** [comment]
@thm cool.  The latest push should fix them both. Thanks!
