### ISSUE TITLE
Hiding toolbar on SERP shows orange background when sliding back in

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#119]
This only happens on the SERP, not the stories pages. If you search something and go to the results, scroll down so that the tool bar hides itself. When you go to scroll back up, the toolbar slides back into view but as it does a large orange background shows up in the space it's sliding into.

**Comment by sreilly** [comment]
@chrismorast is it possible to get a screenshot of this?  I'm fixing a bug related causing the toolbar to not resize into the right location after rotating, but I wonder if this is a separate issue.

**Comment by sreilly** [comment]
@chrismorast @thm I've found and worked around this issue.  There will be a build on hockey in a few minutes with the fix.  It changes how the content views underlap the bottom bar, so if you see any more scrollable content that gets stuck under the bottom tab bar, or content that seems to get stuck about 50pts above it, please let me know! I'll of course continue checking for layout problems like that too.

**Comment by thm** [comment]
@sreilly marking this complete as I'm unable to reproduce the issue again. @chrismorast feel free to reopen if you still see it!

**Comment by chrismorast** [comment]
looks like this has been addressed!
