### ISSUE TITLE
Status Bar

### ISSUE THREAD

**Issue by ghost** [duckduckgo/ios-search-and-stories#12]
On iOS 7 it's clear the status bar needs some attention.

There are three options to resolve this (_ordered by amount of time required to implement_):
1. Hide the status bar completely
2. Reduce the size of the parent `UIWindow` by 20pts, and then offset it's `x` position by the same amount. This would bring the appearance of the status bar in-line with all previous versions of iOS
3. Nudge the _content_ down by 20pts on each view, and take advantage of the newer iOS 7 APIs to handle the status bar appearance. This would also require some new assets, such as a taller navigation bar graphic. Choosing this route would also allow us to manipulate the colour of the text on status bar, meaning we could transition it from black to white when showing the basement view

![statusbar](https://f.cloud.github.com/assets/20023/2160358/0fc5040a-94b7-11e3-8b3a-edcf89ae45da.png)

/cc @nilnilnil

**Comment by nilnilnil** [comment]
@micpringle https://github.com/duckduckgo/ios/pull/16 had an interim fix before we do #8 right?

**Comment by nilnilnil** [comment]
Nevermind -- still looks broken on TF.

**Comment by ghost** [comment]
This is fixed in #8
