### ISSUE TITLE
Shifting scroll-position in main feed

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#120]
1. So, far I've been unable to reliably reproduce, but you may be able to find what's causing the current web view to peek through:
   ![photo 25-09-15 11 05 11 pm](https://cloud.githubusercontent.com/assets/1379822/10125052/24f8d7a2-6567-11e5-9e19-c4d3e1b83a5a.png)
2. While trying to reproduce the issue in the screenshot above, I found another one. After searching for a certain query, when you select the search-field but tap "cancel" right after, the field is cleared completely rather than showing the current query

**Comment by sreilly** [comment]
@thm I haven't been able to reproduce either of these. I did recently fix some other problems in areas around the search bar and autocompletion.  Can you confirm whether you still see either of these issues anymore?

**Comment by thm** [comment]
@sreilly I still see the second issue. On iPhone it's every time I tap "Cancel", on iPad it seem to only happen after the second time(?)

**Comment by thm** [comment]
@sreilly another small thing, rather than showing a bunch of options can we simply select the query/URL and leave it at that? (like Safari is doing)

![safari-ddg-comparison](https://cloud.githubusercontent.com/assets/1379822/10230739/0b36d9ac-687f-11e5-9430-c74dd6281288.png)

**Comment by sreilly** [comment]
@thm fixed the selection thing.  The upcoming build will select the text but not show the menu.  For some reason it still shows the grabbers on either side, unlike safari, but the menu will not show now.

**Comment by sreilly** [comment]
@thm I'm sorry to have to ask this, but would you be able to make a video of the cancel button thing happening?

**Comment by thm** [comment]
@sreilly [demo](http://cl.ly/0C3t3g1i451g/demo.mp4), when canceling the search the field is cleared and showing the placeholder, while still on the page of the active query

**Comment by thm** [comment]
@sreilly in addition, you can again see the issue here where the Stories feed shifts to a different scroll position. This time we start with a food story, and when returning we get a baby story.

**Comment by sreilly** [comment]
@thm the cancel issue is fixed in the next build.

as for the stories feed shifting, is there any pattern to the shifting?  Does only the main stories view shift?  If you go to the favorites or recents stories tab and then back to the main stories, does it show the same story at the top of the main list that it was showing at the top of the favs/recents list?

**Comment by thm** [comment]
@sreilly 

— Yes, it's only the main stories feed that shifts, and it happens when visiting from any other page (ie. search, favorites, recents, etc).

— When I go to the favorites or recents pages, and then back to the main stories feed, then there's no correspondence between the stories shown, it's completely random. Clearing both favorites and recents doesn't change anything.

— If I _scroll up_ in the main feed, leave, and get back, the view aligns the baby story to the bottom of the screen, and when I _scroll down_ the baby story is aligned to the top of the screen.

— After a cold start, the main feed starts at the top, as expected. Going to favorites/recents and back returns the scroll position of the feed to the baby story like before.

**Comment by sreilly** [comment]
@thm are you still seeing this?  I made some changes a couple of weeks ago that I think should have resolved it, but will take another look if the issue still remains.

**Comment by thm** [comment]
@sreilly Yes, the main stories feed seems to work fine at this moment, but the Favorites and Recents feeds still scroll to a different position on the page than where I left them at. (build 694)

**Comment by chrismorast** [comment]
I see this with the main feed as well. I go to the main stories feed, scroll to the top, select favorites (which has scrolled to the middle of the feed rather than where I left off or the top) the go back to stories and I'm in the middle of the feed rather than the top, which is where I left off.

**Comment by chrismorast** [comment]
Adding another case of this as well (Reported by Brian Risk)
[app-rotation-behavior.pdf](https://github.com/duckduckgo/ios/files/22193/app-rotation-behavior.pdf)

Scroll position not remembered when changing orientations far down the page.
Step 1: Scroll to an article far down the page. That is, let it load more articles, scroll, load, scroll, load, etc
Step 2: Rotate to landscape
Step 3: rotate to portrait
The behavior is that we are no longer at the point we started at for step 1. We are further up the page. For me, rotating from portrait to landscape, back to portrait works for the early articles, but everything after these Appl Car/ VW posts exhibits this behavior.

**Comment by sreilly** [comment]
@thm @chrismorast can you guys try build 696 which was just posted to hockey?  I rewrote the scroll point saving/restoration so it should be a lot more reliable now.

**Comment by thm** [comment]
@sreilly The scroll position seems to be stored correctly right now! Rotating the device to landscape and back still results in a different scroll position on the main feed though

**Comment by thm** [comment]
Two more related problems:
1. The scroll-position in the search list isn't stored correctly either. When I scroll down the page, and rotate the device to landscape and back, then the scroll position is re-set to the top of the page.
2. The search-field placeholder moves out of place after rotating the device to landscape, and retains its centered position when rotating back to portrait (see screenshot below)

![photo 28-10-15 3 45 29 pm](https://cloud.githubusercontent.com/assets/1379822/10792078/8674cbd0-7d8b-11e5-895a-4a4544014b08.png)

**Comment by sreilly** [comment]
@thm nice catches!  With build 697 I've fixed the problem with the re-centering of the placeholder upon rotation.

As for the other problem, I'm seeing the list shift a bit during the transition between landscape and portrait but in general the top-most visible item is usually kept visible when rotating back to portrait.  The list scroll position upon rotation is handled internally by the iOS/UIKit view so we could possibly override that behaviour but it might risk breaking something else.  Would you mind sending a screen capture video to show this problem?

**Comment by thm** [comment]
@sreilly 

— Watch the sunglasses guy (on the main feed): http://cl.ly/2I370L101P0i/sunglasses.mp4
— Watch "tesla news" (in the search list): http://cl.ly/1M320d400j2L/tesla-news.mp4

**Comment by sreilly** [comment]
@thm ok, so the "tesla news" shifts a bit because upon rotation we are updating the history section because we wanted to show fewer entries in landscape than in portrait.  When I disable that refresh it keeps the right location relative to the top of the screen.  I've just pushed this change, as I think it's better to preserve the scroll location than to adjust the number of values when rotating.  It'll still show a different number of recent entries if you open in landscape vs portrait.

Checking on the stories view now!

**Comment by sreilly** [comment]
@thm build 701 now manually overrides the built-in scroll view adjustment to try and put the first fully-visible story at the same vertical offset when you rotate it.  Can you give it a try?

**Comment by thm** [comment]
The main feed still shifts down the page about ~20px every time I rotate the screen. I wonder if it has to do with the 20px we add at the top of the mosaic view in landscape mode.

**Comment by thm** [comment]
@sreilly The search list also still seems to shift up after rotating to landscape and back. It's not all the way to the top anymore though. Other than that I can't reproduce any noteworthy shifting in the story feeds.

**Comment by ghost** [comment]
In regards to text selection, it is very difficult to choose the bang button [!] on the left of the selected query. Sometimes it works right away, but for the most part, the app thinks I'm trying to activate options for the selected text, like cut, paste, define, etc.

I don't know how much room is given for selecting the bang; perhaps an increase would be the easiest fix. I personally don't feel the need to automatically select text when I tap the search bar. Why is it selected by default? There is an (x) for clearing the search bar with one tap, so I don't know why the selection is necessary.

Perhaps it is useful for some people, and for that reason, I don't want to suggest changing the default text selection behavior without knowing how people expect the app to function.

Thanks

**Comment by SwiftlyDeft** [comment]
@thm Could you confirm that this scroll shifting is still and issue? Thanks

**Comment by thm** [comment]
@SwiftlyDeft in the latest build (v743) this issue still occurs. When switching between landscape and portrait mode a few times you'll notice that the page scrolls down with ~20px increments. However, it's a minor issue. I doubt people are going to switch device orientation often enough to be really bothered by it. If it's an easy fix, feel free to go for it, otherwise feel free to mark this complete!
