### ISSUE TITLE
Bangs autocomplete issues

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#121]
1. From a cold start, the bangs autocomplete list doesn't scroll all the way, so the bottom few results are covered by the keyboard
2. Bangs in the autocomplete list flicker and often jump around when tapping the bangs-icon

**Comment by sreilly** [comment]
@thm The first issue should now be resolved in the build on hockey.  Are you still experiencing the second?  I can't seem to reproduce it on iPhone or iPad.

**Comment by thm** [comment]
@sreilly yeah, I still see it and can reproduce on both iPhone and iPad. Immediately after I tap the bangs-icon autocomplete will show a short list of available bangs. Rather than them showing up instantly, they sort of appear with the active/touched state on and then transition (read: flicker and jump) for a second back to normal. Then it's all good.

**Comment by thm** [comment]
@sreilly It seems to be the most apparent after a cold start. After the first time it's less apparent but still visible. Here's a demo right after tapping the bangs-icon: http://cl.ly/1Y2E2C0K2X1w/demo.mp4

**Comment by sreilly** [comment]
@thm Can you try the latest build (in a couple of minutes)?  I believe it may resolve this, but I've only tested on one device so far.

**Comment by thm** [comment]
@sreilly I'm still seeing the list-items jumping around (build 694). They seem to really quickly transition in from the top. The grey flickering seems to be gone however.

**Comment by sreilly** [comment]
@thm ok, I think build 695 works around that other transition issue.  No idea why that was happening, but should now be resolved!

**Comment by thm** [comment]
@sreilly perfect, thanks
