### ISSUE TITLE
Tabbar tweaks

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#122]
1. Can you move the icons a bit more closer together so that they appear less disconnected? The difference for the two outer icons in a 5-icon tabbar is 120px/60pt each. I would strive for the same distance inbetween icons on the 4-icon tabbar we have for Search
2. It could be the color-profile of the screenshot, but it seems icons appear darker than designed(?)

top = current, bottom = new
![comparison](https://cloud.githubusercontent.com/assets/1379822/10147693/da7f590c-662f-11e5-93b8-96d751d02b31.png)

**Comment by sreilly** [comment]
@thm Yes, this is pretty odd.  Most of the colours are actually appearing darker than in the mockups, despite using the hex codes provided.  The refresh/reload control is the same way.  I'll take care of it.

**Comment by SwiftlyDeft** [comment]
Brought the tab bar items closer in for the iPad, only. This will be available in the next beta build

**Comment by thm** [comment]
@SwiftlyDeft looks good, thanks!
