### ISSUE TITLE
Story-icon placeholder

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#123]
@sreilly can you give the story icons a #ddd background, so that when they don't load at least the text looks properly aligned?

![comparison](https://cloud.githubusercontent.com/assets/1379822/10160611/f0361640-669e-11e5-9fcb-1dda2ae6433a.jpg)

**Comment by sreilly** [comment]
@thm done; build available on hockey now

**Comment by thm** [comment]
@sreilly can't reliably test this as my internet is too fast, I'll trust you on this one :)
