### ISSUE TITLE
Inconsistent width on segmented tabbar

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#124]
I'm posting this here again, as this doesn't seem to be fixed yet:

![img_5244](https://cloud.githubusercontent.com/assets/1379822/10231066/0309e204-6881-11e5-84ad-d432d55f207e.PNG)

cc @chrismorast

**Comment by chrismorast** [comment]
It looks like when the screen is rotated to landscape, the narrow version of the tabbed remains but when the user rotates back to portrait, the wide version (meant for landscape view) is then displayed.

**Comment by sreilly** [comment]
@chrismorast which build do you have?

**Comment by sreilly** [comment]
@chrismorast Ah, I can tell from the mosaic mode title heights that this is an old version.  If you get the latest from hockey this is fixed.

**Comment by sreilly** [comment]
@chrismorast  oops, nevermind those last two comments.  Looks like theres also a bug in the title bar heights.

**Comment by thm** [comment]
@sreilly please read the title again, this is about the segmented tabbar below the search-field. Its width changes wrongly when rotating the screen. They're old screenshots, but the issue still occurs. I'm on the latest build. Don't make me post another demo video :)

**Comment by sreilly** [comment]
@thm @chrismorast Ah, got it.  Should now be fixed in build 675, coming soon to a hockey near you :)

**Comment by thm** [comment]
@sreilly thanks, the only thing left to do now is fixing all the margin and alignment issues:

![inconsistent-margins](https://cloud.githubusercontent.com/assets/1379822/10245461/fe6614e8-6907-11e5-9e9b-b2d0da85d1e0.jpg)

**Comment by sreilly** [comment]
@thm I see the misalignment in the segment bar (fixed, pushed) but the spacing on the sides of the address bar matches your designs in my measurements.

Now I see in the Measurements pngs you provided that the 1_search.png shows 20px/10pts between the screen edge and the search field.  The 2_stories.png file shows 15px (which I've had to round to 8pts) but the search field is inactive.  Which measurement should we go with for that space, or should I go with 10pts for an active search field and 8pts for inactive?

**Comment by thm** [comment]
@sreilly I've noticed that, sorry about that. As far as I know it should be 16px/8pt all around the search-field and the segmented tabbar, all the time.

**Comment by sreilly** [comment]
@thm pushed it to 8pts all around.  build should be there now!

**Comment by thm** [comment]
@sreilly in the latest build available (678) the segmented tabbar still has 20px/10pt on either side, rather than 16px/8pt. Other than that, looks good!

**Comment by thm** [comment]
@sreilly looks fixed, thanks!
