### ISSUE TITLE
Rephrase "clear recents" confirmation

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#126]
**Description**: "Are you sure you want to clear your recents? This can not be undone."
**Button**: "Clear Recents" (with an "s")

![screenshot](https://cloud.githubusercontent.com/assets/1379822/10247220/e9bd330e-6917-11e5-9e02-e5759cf1cde5.png)

**Comment by sreilly** [comment]
@thm done, thanks!
