### ISSUE TITLE
Landscape empty states outside viewport

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#127]
In landscape, empty states seem to fall outside the viewport, with no way to scroll the last line into view.
![screenshot](https://cloud.githubusercontent.com/assets/1379822/10247364/dfc77b06-6918-11e5-9a20-a72a72775e9c.png)

Can you change the margins slightly based on the comparison below, with one addition for landscape mode: in landscape mode, the entire block should be moved up an extra 40px/20pt to make it properly vertically centered. Even better would be to have it vertically centered automatically, so that it works on iPhone 5< screen sizes seamlessly, larger sizes (iPhone 6+, iPad) aren't necessarily of concern since everything would be in view there.
![measurements](https://cloud.githubusercontent.com/assets/1379822/10248101/cc41cb68-691d-11e5-98a6-3d1a23e419f4.png)

**Comment by sreilly** [comment]
@thm this should be all set now

**Comment by thm** [comment]
@sreilly rather than moving the icon, title and description closer together as described above they seem to have moved even further apart. Instead of **adding** 10px/5pt above and below the title can you **subtract** that amount above and below the title so these elements get closer together?

**Comment by sreilly** [comment]
@thm oops... I'm not sure how that happened.  I've tweaked it to match the design above, with the exception of the icon + title + subtitle being vertically centered in the view.  I did that to be consistent depending upon orientation, however it can definitely be tweaked.  Anyway, fixes have been pushed :)

**Comment by thm** [comment]
@sreilly thanks, this works for now
