### ISSUE TITLE
Revert back to small titles on mosaic view

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#129]
@sreilly we would like to revert the mosaic view back to using small titles for the large stories. So, essentially making the large story's images slightly taller to line up the title box with that of small stories. Would this be an easy fix or do you think we should push this off to the 'iteration 1' milestone?

cc @chrismorast 

(left: current, right: next)
![comparison](https://cloud.githubusercontent.com/assets/1379822/10402276/ba972f1e-6ec4-11e5-8d33-dbabab033fc4.jpg)

**Comment by sreilly** [comment]
should be a piece of cake!

**Comment by sreilly** [comment]
@thm just to confirm, this was done earlier today and pushed to hockey.

**Comment by thm** [comment]
Thanks, noticed it!
