### ISSUE TITLE
ability to save images from stories

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#13]

**Comment by quanganhdo** [comment]
Do you mean to provide a 'Save Image' option when an image is long pressed in the web view?

**Comment by nilnilnil** [comment]
Yes

On Saturday, February 22, 2014, Anh Quang Do notifications@github.com
wrote:

> Do you mean to provide a 'Save Image' option when an image is long pressed
> in the web view?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/duckduckgo/ios/issues/13#issuecomment-35795211
> .

## 

caine. opensesame.st

**Comment by ghost** [comment]
#13

**Comment by ghost** [comment]
@nilnilnil I've just pushed a commit that adds this functionality. It was inspired by the work @quanganhdo did, but hooks into the existing popup menu rather than presenting an action sheet. It also doesn't remove or conflict with any of the existing functionality.

**Comment by nilnilnil** [comment]
Thanks @micpringle and @quanganhdo!
