### ISSUE TITLE
Settings not stored

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#130]
@sreilly Any settings set in duckduckgo.com/settings aren't stored after restarting the app. Settings are active in the current session but after a cold start all preferences are reset to default.

**Comment by thm** [comment]
In Safari, everything works as expected

**Comment by sreilly** [comment]
When the app is stopped (not just sent to the background, but terminated) the cookies and any local storage are intentionally cleared.  Would you like to change that, or make it an option?

**Comment by sreilly** [comment]
@thm  When the app is stopped (not just sent to the background, but terminated) the cookies and any local storage are intentionally cleared. Would you like to change that, or make it an option?

**Comment by thm** [comment]
@sreilly no, it turns out that's intentional. It's a false alarm.
