### ISSUE TITLE
Make subtitles smaller

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#135]
Left = current DDG, right = default in iOS:
![comparison](https://cloud.githubusercontent.com/assets/1379822/10513603/11512d22-7349-11e5-959c-ca90a567bc06.png)

cc @chrismorast

**Comment by sreilly** [comment]
@thm fixed for the next build!

**Comment by thm** [comment]
@sreilly Thanks, looks much better! Can you move the subtitles up a bit so that they're slightly closer to the title? (probably about 2-4px). I also noticed the currently-selected value for the main-menu items have gotten the same small font-size, which they shouldn't have had. :) Purple arrows in the screenshot attached:
![screenshot](https://cloud.githubusercontent.com/assets/1379822/11563715/add88246-99d5-11e5-926b-dc70be42308e.png)

**Comment by thm** [comment]
@SwiftlyDeft (cc @sreilly) it seems the selected-values indicated with purple arrows in the screenshot from my comment above were completely removed in the latest build (731). They should've merely gotten the correct font-size (same as "Home" and "Region" titles).

I also notice that the main settings page now has a blue-ish background, as opposed to the light grey background we have everywhere else. This is especially apparent on the split-view settings page on iPad. Here's a screenshot (see left side of page):
![photo 11-01-16 10 20 18 pm](https://cloud.githubusercontent.com/assets/1379822/12247019/3e94ddf2-b8b2-11e5-95de-27a099d2fd43.png)

**Comment by thm** [comment]
@SwiftlyDeft One more issue I notice on the settings page on iPad (v731) is that the right side of the page covers the tabbar after navigating to a different sub-page (eg. "Sources" or "Readability"). See purple arrows in the screenshot below:
![covered-tabbar](https://cloud.githubusercontent.com/assets/1379822/12247255/70c93a2e-b8b3-11e5-94a7-4613977e63d9.png)

**Comment by SwiftlyDeft** [comment]
@thm, Thank's. The tighter spacing for the iPad needs to be updated to support "split views", top priority to get the tab bar working 100% for iPad.

**Comment by SwiftlyDeft** [comment]
@thm, fixed the tab bar, the left side menu color (not blue!), brought back the detail text/selected text.  I've also added some polish, tapping on a home or region option will actually update the left menu. The settings for iPad should work much better now
