### ISSUE TITLE
When refreshing a readability story the page turns red

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#136]
![photo 15-10-15 7 22 58 pm](https://cloud.githubusercontent.com/assets/1379822/10521970/ea4e21d8-7372-11e5-9e9d-2ce3779c1da6.png)

cc @nilnilnil

**Comment by thm** [comment]
How to reproduce (image courtesy of @chrismorast). Again, only applies to readability stories:

![red-screen](https://cloud.githubusercontent.com/assets/1379822/10522284/a84c59c4-7374-11e5-9f84-466ccbb3db8a.jpg)

**Comment by sreilly** [comment]
@thm all fixed, thanks!
