### ISSUE TITLE
Search-field issue

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#138]
@sreilly I feel like we've solved this issue before, but apparently it's back. How to reproduce:
1. Search for something (eg. "apple")
2. Tap the back button ("<" on the tabbar)
3. Tap search-field
4. Tap "Cancel"
5. RESULT: "apple" appears back in the search bar, with no way of getting rid of it from the tab.  Going to the "stories" tab and back clears it from the search bar, but the auto-complete is still based off the prior search -- hitting "cancel" again, it reappears.

**Comment by sreilly** [comment]
@thm This is fixed for the next build!  I'll have the automated builds up and running again soon since I've changed the git repo layout a bit.

**Comment by thm** [comment]
@sreilly thanks!
