### ISSUE TITLE
Crashes on older iPhones running older versions of iOS

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#140]
@sreilly We've gotten several reports of the new app crashing on an iPhone 4(s) with iOS 7 immediately after the preload screen. Do you think this is related to performance issues? Something we can easily address?

**Comment by sreilly** [comment]
@thm I'll check it out right now.  I'm sure we can handle it :)

**Comment by thm** [comment]
Got a report for iPhone 5s on iOS 7 too. Maybe that helps scoping the issue, as it seems to be iOS 7 is where it's at.

**Comment by sreilly** [comment]
@thm ok, I've fixed it.  build 704 coming shortly with the fix. If we can try it out quickly (including on non-iOS7/iPhone4s) and everything else seems fine then I can request an expedited review with Apple.

**Comment by sreilly** [comment]
@thm @nilnilnil @chrismorast build 705 fixes the crash and is now waiting for review with Apple.  Can you guys try it out on your regular phones and see if anything else is broken as a result of these changes?  If you give me the all clear I will request an expedited review.

**Comment by thm** [comment]
@sreilly I'm not sure if it's a result of these changes but the search-field placeholder is centered when going to the search tab after a cold start. Afterwards it's left-aligned correctly. I also don't continuously get auto-complete to show up when typing a query, it appears and disappears while typing.

**Comment by sreilly** [comment]
@thm just an FYI that I see this too and nearly have this fixed as well

**Comment by thm** [comment]
@sreilly awesome, thanks!

**Comment by sreilly** [comment]
@thm ok, that is also fixed and will be included in build 707, which is due any minute now.  Can you let me know if I can go ahead and submit it?

Because I hastily included Caine's 3d-touch shortcut PR into the main 2015-refresh branch this build will also include that code.  I have however updated that code and I think it's acceptable to include in this build.  Would you mind if I included the new shortcut/force-touch bit in the submission?

**Comment by tbegonja** [comment]
DuckDuckGo is also crashing on a 5c under iOS 7.

**Comment by thm** [comment]
@sreilly yup, the issues seem to be fixed with v707. I'm unfortunately not able to test the 3D-touch addition (no 6s here), but if you've reviewed it and are confident that it won't affect the app's internals in a negative way, then I'm fine with its inclusion!

**Comment by sreilly** [comment]
@thm @nilnilnil ok, it's submitted and waiting for review.  I don't have permission in iTunesConnect to request an expedited review, but if you or Caine do can you submit the expedited review request at this link?  https://developer.apple.com/appstore/contact/?topic=expedite

They'll likely ask for the app ID (663592361) and app bundle ID (com.duckduckgo.mobile.ios).  Thanks!

**Comment by nilnilnil** [comment]
done.

**Comment by sreilly** [comment]
@thm it was a result of those changes but should have been fixed by build 707.

**Comment by tbegonja** [comment]
I deleted the app, re-downloaded it from the iOS App Store, did a hard-reset on my phone, and the app STILL behaves the same as it did before: it never leaves the splash screen and immediately transfers control back to the Home Screen/Finder.  Switch back to the app by either tapping on the app icon or by navigating to it via the list of running apps, and it behaves the same: never stops displaying the splash screen and goes back to the Home Screen/Finder.As before iPhone 5c running iOS 7.0.6.-----Original Message-----

**Comment by thm** [comment]
@tbegonja with which version of the app are you experiencing the issue? Did you update to the just-released version? (v6.0.1)

**Comment by tbegonja** [comment]
The version I downloaded last night was version 6.0.While I have since deleted that, I find that the App Store report "Unable to Download App 'DuckDuckGo Search & Stories' could not be downloaded at this time." when I try to download it.-----Original Message-----
