### ISSUE TITLE
Mosaic view completely broken in the new build (6.0.1)

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#142]
These are screenshots from iPad using iOS 8 as well as iPhone 6 using iOS 9.1
![img_0390](https://cloud.githubusercontent.com/assets/7061920/11056488/2c57764c-8737-11e5-9de6-a5583abb31c2.png)
![img_5613](https://cloud.githubusercontent.com/assets/7061920/11056489/2c7d0be6-8737-11e5-8003-410cae8843da.PNG)

cc @thm @nilnilnil

**Comment by thm** [comment]
@chrismorast thanks for reporting, this looks really bad! @sreilly have you been able to reproduce the issue?

**Comment by sreilly** [comment]
@chrismorast @thm This really does look terrible.  I've never seen this in the main stories view or the favorites view before, but will track it down ASAP.

**Comment by sreilly** [comment]
@chrismorast @thm Part of one of the changes related to the iOS7 crash workaround was causing the problem.  I've reverted that part of the workaround and pushed it as version 6.0.2.  I'll have to test it on an iPhone with iOS7 in the morning, but I'm confident that this won't be a problem even on iOS7.  I apologise for the bug... this looks really bad.

**Comment by sreilly** [comment]
@thm just a ping that I believe this one can be closed now
