### ISSUE TITLE
Viewport height issue

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#143]
How to reproduce:
1. Search for "bike share san francisco"
2. Tap a tile in carousel to initiate the map-view
3. RESULT: When tabbar is visible the viewport extends below tabbar, 

![img_5579](https://cloud.githubusercontent.com/assets/1379822/11060125/820b19e2-879e-11e5-8d5a-b9162ad8e04e.PNG)

cc @chrismorast @bsstoner @nilnilnil

**Comment by sreilly** [comment]
@thm I believe this needs to be fixed on the web side of things. I'm not too familiar with css, but I think that div should be pinned to the bottom of the viewport in a way that is updated when the viewport/inset changes.

**Comment by SwiftlyDeft** [comment]
![143-safari reference](https://cloud.githubusercontent.com/assets/4774399/12134479/7edb6ec0-b494-11e5-9da0-d65b77b21e5f.PNG)
@thm On Safari mobile, I'm able to reproduce the same issue that we are experiencing in-app. The attached image shows a grey bar behind the bike location cards, they look like the space that we need the cards to move up by. 

To Reproduce:
Drag the web page up slowly, you should see Safari's tab bar scrolling down slowly and you should see the bar.

**Comment by SwiftlyDeft** [comment]
![img_3557](https://cloud.githubusercontent.com/assets/4774399/12134613/dfe7bc4a-b495-11e5-8846-a36bd670adcd.PNG)

@thm This screenshot was taken in safari as well but it's not in being scrolled. 
Ive checked Chrome on iOS, and the responsive site on IE works great so the issue here is the animating tab bars and how the site is responding to it. 

Where should we place this issue and can it get closed on the iOS end. 

Thanks
Josiah Clumont

**Comment by thm** [comment]
Thanks @SwiftlyDeft for looking into this. I'll have this reassigned to front-end. cc @bsstoner

**Comment by SwiftlyDeft** [comment]
Thanks @thm, i'll be looking at a Hybrid solution this week where we may be able to run a javascript function through the Web View that could animate the desired changes better. If there's a way to include me on the issue on the front end i would like to be apart of solving this issue for all of us. Thanks

**Comment by thm** [comment]
@SwiftlyDeft @bsstoner I just noticed on websites like http://qz.com and http://medium.com, that have fixed elements at the bottom of the page on mobile, that these elements are hidden below the tabbar in the app but properly float above the tabbar on mobile Safari. What do you think of setting up a call this week to discuss the issue? that may be more efficient

**Comment by SwiftlyDeft** [comment]
@thm @bsstoner , works with me for a call to sort this out.
