### ISSUE TITLE
Grey border on app icon

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#146]
@sreilly the grey border on our app icon is not in the image assets as far as I know. In the attached screenshot Vimeo has grey lines too. It's a little faint in the screenshot, but is this something we can solve?

![cwkr6-lwuaa5bqa jpg-large](https://cloud.githubusercontent.com/assets/1379822/11787008/fa14d2b0-a289-11e5-93b0-c0aeacf445b7.jpeg)

Source: https://twitter.com/fabiodomar/status/676263344907644928
cc @chrismorast @yegg

**Comment by sreilly** [comment]
@thm Oh wow, that grey line does seem to exist in the app icon's png files.  I've attached a screenshot showing them opened in Preview and zoomed in. I don't think we did any processing on these files when adding them to the project.  Do you have the originals?

<img width="482" alt="screenshot 2015-12-14 22 40 00" src="https://cloud.githubusercontent.com/assets/470762/11796348/c26dc572-a2b3-11e5-8ae8-0bde0e610e76.png">

**Comment by thm** [comment]
@sreilly you're right! I think it must have gone wrong when converting one asset to all the other required sizes, weird stuff! I'll get new assets sorted

**Comment by thm** [comment]
@sreilly all done, the updated assets are on BTS

**Comment by sreilly** [comment]
@thm thanks! Just pushed a build with them.  I've been making some more progress with the tab bar sliding out.  Hopefully something worth pushing soon!

**Comment by sreilly** [comment]
@thm one more thing is that apple now wants an 83.5x83.5 pt icon at 2x resolution (so 167x167px).  If you still have the original handy could you generate one of that size?

**Comment by thm** [comment]
@sreilly sure, added!
