### ISSUE TITLE
App crashes when the send feedback button inside the settings view is clicked

### ISSUE THREAD

**Issue by cipherself** [duckduckgo/ios-search-and-stories#159]

**Comment by tagawa** [comment]
Thank you very much for reporting this @skeuomorf

**Comment by tagawa** [comment]
Actually, could you let us know what version of iOS you're using?

**Comment by cipherself** [comment]
> Thank you very much for reporting this @skeuomorf

No prb :)

> Actually, could you let us know what version of iOS you're using?

Version 9.3.2 on an ipad air.

**Comment by tagawa** [comment]
Thanks @skeuomorf

**Comment by sreilly** [comment]
I see the problem here... we're not checking if MFMailComposeViewController.canSendMail.  I've fixed it and will send over a pull request ASAP.

**Comment by sreilly** [comment]
@skeuomorf the crash is likely occurring you probably don't have any mail accounts set up in the Apple Mail app.  A temporary workaround would be to set up an email account - that will let you send email from most other applications that use the built-in iOS share-to-email function.  Please let me know if that doesn't sound like the issue.

**Comment by cipherself** [comment]
@sreilly Thanks for pushing a fix! I've also tried the workaround and it works.
