### ISSUE TITLE
Feature Request: Support URL Schemes

### ISSUE THREAD

**Issue by tommytwoeyes** [duckduckgo/ios-search-and-stories#164]
It would really enhance the usefulness of the DDG app if it registered and supported a URL scheme (e.g. **ddg://** or **duckduckgo://**) so that the app could be opened interactively from not only other apps in general, but especially from iOS automation tools like [Workflow](https://workflow.is) and [Launch Center Pro](http://contrast.co/launch-center-pro/).

**Comment by edgesince84** [comment]
thanks for the suggestion @tommytwoeyes.  I'll bring this up internally.

**Comment by tommytwoeyes** [comment]
Thanks bro

**Comment by sreilly** [comment]
@tommytwoeyes @edgesince84  this should already work... if you search with a url such as 
`duckduckgo:///?q=<url-encoded-search-terms>`

You can also invoke the app and go straight to the query form by omitting the 'q' parameter to the URL.  I use Launch Center Pro myself and just noticed that they already have support for the invoking DuckDuckGo Search & Stories with a query in their built-in list, so the URL in their auto-created launch button should be an easy path to setting it up.

Thanks!
Sean
