### ISSUE TITLE
Flickering error

### ISSUE THREAD

**Issue by jc86035** [duckduckgo/ios-search-and-stories#19]
On the iOS Search and Stories app, after reading a news item and returning to the menu, all the story icons start to flicker, and while the buttons still can be pressed, scrolling doesn't work. The application has to be restarted for it to work.

OS: iOS 7.0–7.0.6, 7.1
Model: iPhone 4s

**Comment by sreilly** [comment]
Hello!  Thanks for reporting this issue.  Are you using the beta version installed from testflight or the current version on the app store?

**Comment by jc86035** [comment]
The current version, from the Store.

**Comment by sreilly** [comment]
Ah ok, in that case it's already been fixed and our next update on the app store should correct the problem (along with a bunch of other improvements).

Thanks for the report!

**Comment by nilnilnil** [comment]
@sreilly We've been seeing it in the TF build as well.

**Comment by ghost** [comment]
@nilnilnil

Thanks for the video.

We've _finally_ been able to track this down and fix it (_for definite this time!_).

Could you all please try the latest build on Hockey?

**Comment by nilnilnil** [comment]
Will do!  What was it?

caine. opensesame.st

**Comment by ghost** [comment]
@nilnilnil 

It was some legacy code that only got triggered in low memory situations. It reset the image cache, but did so in a way that caused the table view to reload itself infinitely, hence the flicker.

**Comment by ghost** [comment]
@nilnilnil Have you or anyone else experienced this since I pushed the fix? If not, you should be good to close this issue.

**Comment by nilnilnil** [comment]
nope.
