### ISSUE TITLE
DDG-iOS user agent for all requests to DDG, not just WatrCoolr.

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#21]

**Comment by ghost** [comment]
It appears as though the header _is_ being set when searching using the search bar:

![search01](https://cloud.githubusercontent.com/assets/20023/2861914/bad7b7c0-d1e8-11e3-836a-4d848ce5eeb2.png)

![search02](https://cloud.githubusercontent.com/assets/20023/2861916/c0c067fe-d1e8-11e3-945b-6db553643a47.png)

But is overridden by `UIWebView` when you actually load the page:

![search03](https://cloud.githubusercontent.com/assets/20023/2861935/3428f99a-d1e9-11e3-86c2-0d4135b84cc2.png)

This appears to be standard behaviour on iOS, but I'm currently investigating to see if the headers set automatically by `UIWebView` can be overwritten.

As an aside, the User Agent string seems to use the build number, which changes with each build we push to Hockey.

**Comment by quanganhdo** [comment]
There's a way to overwrite that (I've done that in one of my apps). I'll look into it this weekend if you want.

**Comment by ghost** [comment]
Thanks @quanganhdo but I've just pushed a commit that fixes that.

**Comment by ghost** [comment]
Here's a request sent via the search bar:

![search04](https://cloud.githubusercontent.com/assets/20023/2862355/7fb22e70-d1f0-11e3-8e8f-02975f9a523d.png)

Here's the search results being loaded in the web view:

![search05](https://cloud.githubusercontent.com/assets/20023/2862357/8a562610-d1f0-11e3-85f2-e84814e0a68c.png)

And here's a non-DDG web page being loaded from the results, in the web view:

![search06](https://cloud.githubusercontent.com/assets/20023/2862360/9fd27836-d1f0-11e3-8794-c14ac3cd4cea.png)

As you can see, the User Agent is only manipulated on the first two.

This functionality is available in the latest build on Hockey. Give it a shot @nilnilnil and see what you think. Let me know if you notice any unusual behaviour.

**Comment by ghost** [comment]
@nilnilnil Are you happy for this one to be closed now?
