### ISSUE TITLE
ellipsize middle string on autocomplete entries.

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#22]

**Comment by ghost** [comment]
@nilnilnil Is this the kind of thing you were looking for?

![middle truncation](https://cloud.githubusercontent.com/assets/20023/2945015/2f59bf08-d9dc-11e3-80ba-42b974316f34.png)

**Comment by nilnilnil** [comment]
Never mind - can we just revert?  I'll do it on the back end.

**Comment by ghost** [comment]
@nilnilnil Yeah no problem. I'll roll-back the change and push another build.

**Comment by ghost** [comment]
@nilnilnil Another option we have which Sean suggested is to truncate the head, and then dynamically reduce the text size, to a minimum limit so the text remains legible.

![ios simulator screen shot 12 may 2014 15 10 53](https://cloud.githubusercontent.com/assets/20023/2945274/6419c2bc-d9df-11e3-8b21-1b777bb44898.png)

**Comment by ghost** [comment]
@nilnilnil Here's a better shot where you can see the dynamic sizes:

![ios simulator screen shot 12 may 2014 15 16 25](https://cloud.githubusercontent.com/assets/20023/2945346/0ecebb36-d9e0-11e3-821e-4141547615af.png)

**Comment by nilnilnil** [comment]
I think we should just revert it entirely and I should handle it all on the server side so we don't have to duplicate code on Android when we start over there.

**Comment by ghost** [comment]
@nilnilnil The changes were never pushed, so there's nothing to revert :smile: Feel free to close.

**Comment by nilnilnil** [comment]
:+1:
