### ISSUE TITLE
smaller text for autocomplete when not bang search

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#23]

**Comment by ghost** [comment]
@nilnilnil 

Is the what @chrismorast mentioned [here](https://github.com/duckduckgo/ios/issues/8#issuecomment-42070096)?

I've updated the alignment, and reduced the cell height so more results appear on screen. It's in the latest build.

Let me know if you still want to go ahead and reduce the font size.

**Comment by nilnilnil** [comment]
I think this is ok.  I'd prefer to talk about ideas like the one outlined in this issue: https://github.com/duckduckgo/ios/issues/22.
