### ISSUE TITLE
quack on refresh broken

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#24]

**Comment by nilnilnil** [comment]
I'm also down with just removing this altogether.

**Comment by ghost** [comment]
@nilnilnil 

This is now fixed (_again, give it a couple of minutes for the build to be pushed to Hockey_).

Bare in mind that it's only setup to _quack_ when there are new items. This could be changed to _quack_ whenever a refresh is triggered regardless of whether or not there are new items. Let me know.

**Comment by nilnilnil** [comment]
neat -- I didn't know that's how it works.  makes it much less annoying...
