### ISSUE TITLE
Update search URL to use next

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#27]
next.duckduckgo.com

**Comment by nilnilnil** [comment]
@micpringle I'd like to prioritize this.

**Comment by ghost** [comment]
@nilnilnil I shall get onto this now.

**Comment by nilnilnil** [comment]
thanks!

**Comment by ghost** [comment]
@nilnilnil 

Ok, that's done :thumbsup: 

Give it a few minutes for the build to be pushed to Hockey and then give it a spin.

**Comment by nilnilnil** [comment]
cool -- I just want to make sure next is working with it beforehand! :smile:

**Comment by nilnilnil** [comment]
Actually, sorry to do this to you; but can you make it `bttf.duckduckgo.com` so we can get updates faster than to the beta site.

**Comment by nilnilnil** [comment]
Close whenever that's in.  Sorry for the confusion.  I just realized we have a PR that will bring the AnswerBar into the mix! :smile:

**Comment by ghost** [comment]
@nilnilnil 

No worries; I've updated the URL.

The new site really does look great on mobile :thumbsup: 

AnswerBar?

Afraid I can't close these, only comment.
