### ISSUE TITLE
Move search URL back to https://duckduckgo.com

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#28]

**Comment by ghost** [comment]
@nilnilnil 

The search and sharing URLs now use https://duckduckgo.com, but the search suggestions still uses https://bttf.duckduckgo.com. Is that okay?

(_if I change the suggestions URL it returns an error and a webpage rather than the suggestions JSON_)

**Comment by nilnilnil** [comment]
No.  They both need to be reverted.

**Comment by nilnilnil** [comment]
Point ac to ac.duckduckgo.com.
