### ISSUE TITLE
!bang causing app to crash during autocomplete

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/ios-search-and-stories#3]
https://twitter.com/jeffpar/status/421836508216053761

thanks to jeffpar for reporting:

"@jeffpar: @duckduckgo In the iOS app, if I begin a search with “!oyez “ the app crashes right after the space."

**Comment by ghost** [comment]
I'm unable to recreate this crash in either the sim or on a device.

@zekiel Are you able to get the app to crash?

It would be good if we could get the crash logs from either yourself, if you can get it to crash, or the person who originally raised the issue. 

There is a great guide [here](http://help.getpocket.com/customer/portal/articles/500338-how-to-find-the-iphone-ipad-app-crash-logs) for retrieving crash logs. For step 5, it'll be any file with **DuckDuckGo** in it's name.

**Comment by nilnilnil** [comment]
I probably fixed this server side with the update to Autocomplete.  I am unable to recreate either.
