### ISSUE TITLE
!Bang suggestions not including the associated sites' icon

### ISSUE THREAD

**Issue by ghost** [duckduckgo/ios-search-and-stories#33]
@nilnilnil 

I've noticed this morning that the !bang suggestions returned by DDG don't include the sites' icon (_where available_) once you get beyond the !bang.

For instance, if I enter **!a** an image is returned in the JSON:

![screen shot 2014-05-29 at 10 43 21](https://cloud.githubusercontent.com/assets/20023/3116275/87a49448-e716-11e3-8a56-8fbee81ba1f2.png)

But if I enter **!a headphones** or **!amazon headphones** only suggested phrases are returned in the JSON:

![screen shot 2014-05-29 at 10 54 26](https://cloud.githubusercontent.com/assets/20023/3116302/4743754e-e717-11e3-9aa3-a2c224c19387.png)
![screen shot 2014-05-29 at 10 43 34](https://cloud.githubusercontent.com/assets/20023/3116283/b655e512-e716-11e3-93a3-0cc887f0cfb4.png)

If a sites' image was returned alongside the phrase when using the !bang it'd make for a much richer experience and would also allow us to provide some context with the suggestions.

**Comment by nilnilnil** [comment]
I'd like to table this for now.  To do this correctly without doubling the size of the output we will need to adjust the API.

**Comment by nilnilnil** [comment]
Also, in the screenshots here, it does look like the functionality was removed.  Where is the old code that did it? https://itunes.apple.com/us/app/id663592361

**Comment by ghost** [comment]
@nilnilnil Was the above comment meant for #31?

**Comment by nilnilnil** [comment]
I guess? I'm confused by these issues now.

**Comment by ghost** [comment]
> Also, in the screenshots here, it does look like the functionality was removed. Where is the old code that did it? https://itunes.apple.com/us/app/id663592361

The behaviour appears to have changed around March 2013 (_according to the git history_) when the app was migrated to Core Data. Prior to that, more info was cached; after the change only the search text was stored.
