### ISSUE TITLE
app sound doesn't work through dock?

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#39]
No sound coming from the iOS app when using a 3rd party speaker dock but it works fine in iOS Safari using DDG.

**Comment by ghost** [comment]
@nilnilnil 

~~Could you be a little more specific about which sounds aren't coming through the 3rd party speak dock? Are you referring to just the _Quack_ sound, which we manage the playback of internally, or are you referring to any medium that plays sound (_such as an embedded YouTube player_) in the built-in browser?~~

@sreilly has filled me in on the conversations that have taken place prior to this release about this issue.

Could you share with us with dock you're using specifically?

**Comment by nilnilnil** [comment]
@chrismorast was having the problems.  He can better describe what is going on.

**Comment by chrismorast** [comment]
It's a Marley dock. No sound coming through it when using the app but sound works when using DDG in iOS Safari on the same device.
