### ISSUE TITLE
duck mode

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#4]
Add a new home view, in addition to {Stories, Recents, Saved}, that is just a search only mode.  The app should just feature the DuckDuckGo logo and open the keyboard right when the application opens.

**Comment by ghost** [comment]
@nilnilnil Don't forget to include this in #8 :smile:

**Comment by ghost** [comment]
@nilnilnil This was just added as part of #8. Give it a spin, and if you're happy close this issue. If not, feel free to leave any comments and I'll pick them up and resolve.

**Comment by nilnilnil** [comment]
@micpringle i'd like the settings to be called "Search only" instead of "Duckmode" which is confusing.  That's it then close.

**Comment by ghost** [comment]
@nilnilnil This is fixed in the latest build. If you're happy, please close.
