### ISSUE TITLE
Wrong !Bang Favicon used in Menu

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#40]
@micpringle , looks like the wrong icon was used for the bang icons in the menu. Can you please use this one.
![icon_bang](https://cloud.githubusercontent.com/assets/7061920/3359831/c56c8c4c-faec-11e3-96e7-393f4ed8f24b.png)
![icon_bang 2x](https://cloud.githubusercontent.com/assets/7061920/3359830/c56acd62-faec-11e3-93fc-8cc69e3081cf.png)

**Comment by ghost** [comment]
@chrismorast 

The current version was submitted to Apple prior to us making this change. So the build available on Hockey and the code in the repo is using the correct icon, we just need to submit another build to Apple to get these changes on the store.
