### ISSUE TITLE
Image loading issues

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#43]
"Hey guys, I've noticed that there are often images in the app that take forever to load. Do we have size restrictions on the images? If so, are they also applied to a requery?

I'm attaching an screenshot with the immigration story image that had this issue. In addition, It didn't completely."

![photo_31](https://cloud.githubusercontent.com/assets/347240/3527855/5c1c4882-0789-11e4-9c9f-d43d07c4b8b1.PNG)

**Comment by ghost** [comment]
@nilnilnil 

Would you be able to provide me with the actual link to that image on your CDN as it would have been returned by the JSON? The story is no longer listed, but it would be good to be able to test with it locally since we know for definite that image caused problems.

**Comment by nilnilnil** [comment]
http://images.christianpost.com/full/56268/latino-hispanic-immigration.jpg?w=658&h=438&l=50&t=40

**Comment by ghost** [comment]
@nilnilnil 

This image downloads just fine for me. I used Apple's [Network Link Conditioner](http://nshipster.com/network-link-conditioner/) to simulate different network scenarios including Wifi, 3G, Edge and poor network conditions, and each time the story images still downloaded.

![wifi](https://cloud.githubusercontent.com/assets/20023/3550194/b568ed44-08d5-11e4-88bd-04639c04c31c.png)
![3g](https://cloud.githubusercontent.com/assets/20023/3550195/b8fd793e-08d5-11e4-81de-b45b0aca3097.png)
![edge](https://cloud.githubusercontent.com/assets/20023/3550196/bbf9a4be-08d5-11e4-9a40-520ecda2409e.png)
![very bad network](https://cloud.githubusercontent.com/assets/20023/3550198/bee0bb54-08d5-11e4-8794-00e79f4f9895.png)

Is this issue something you're seeing all the time, or is this the first incident you're aware of?

**Comment by nilnilnil** [comment]
I think it was a fluke. Also, we made some changes yesterday to reduce latency. Closing for now.
