### ISSUE TITLE
All text in landscape view goes to title size.

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#44]
@micpringle @nilnilnil , when I turn my phone to landscape in readability view all text converts to title size. @micpringle please assign to @nilnilnil if this is not something that should be in your court. Thanks.
![photo 1_20](https://cloud.githubusercontent.com/assets/7061920/3567003/4afedf1c-0b0b-11e4-8525-0ef5d50ce2c6.PNG)

**Comment by ghost** [comment]
@chrismorast 

I've taken a look at how readability mode is implemented and it appears we don't apply any styling locally; the returned HTML for the story includes a link to a [CSS file](http://duckduckgo.com/watrcoolr/css/article_113.css) which is responsible for the styling. I guess it'll be this which needs to be updated to account for the viewport switching to landscape.

Have re-assigned to @nilnilnil

**Comment by thm** [comment]
I'm closing this since readability-view is done internally
