### ISSUE TITLE
@3x assets for iPhone 6 Plus

### ISSUE THREAD

**Issue by ghost** [duckduckgo/ios-search-and-stories#46]
@chrismorast 

Would you be able to provide @3x versions of all the assets used in the app so we can make sure it looks great on the new iPhone 6 Plus?

**Comment by chrismorast** [comment]
Of course! is there a library that I can have access to so I don't miss any?

**Comment by ghost** [comment]
Hey @chrismorast 

You can find the asset catalog where most images are stored [here](https://github.com/duckduckgo/ios/tree/master/DuckDuckGo/Images.xcassets).

Other than that, it might also be a good idea to read through issue #8 to catch any that aren't in the asset catalog (_for legacy reasons_).

**Comment by chrismorast** [comment]
@micpringle how would you like me to get these to you? Seems like a pain to have to post each individual PNG here.

**Comment by chrismorast** [comment]
@micpringle , I've posted the assets to Dropbox. Let me know if there are any issues or if I've missed something.

https://www.dropbox.com/sh/pizqthtgz5ao2v0/AAAheIADHskay-a4nefD4IWZa?dl=0

Thanks!

**Comment by ghost** [comment]
@chrismorast I think you got every one, thanks!

Moving forward, we now have to supply a new type of launch image. I'm knocked one together using the logo from the First Run screen, but you'll probably want to change it.

![launch](https://cloud.githubusercontent.com/assets/20023/4285280/fd343032-3d84-11e4-8407-32ba7a5e61e7.png)

Let me know how you'd like to proceed.

**Comment by chrismorast** [comment]
Actually, I'd like to change this to use our DDG salmon color background (the same color we use in the PTR background). Can you give me the dimensions that I would need to do these in?

It would be something like the attached example.
![test](https://cloud.githubusercontent.com/assets/7061920/4290662/a6cc7e64-3dbd-11e4-96af-b3453324acf8.jpg)

**Comment by chrismorast** [comment]
Here's what I assume you would need. Let me know if I'm wrong :)
![launch-image](https://cloud.githubusercontent.com/assets/7061920/4291793/610c2082-3dc7-11e4-85b3-01e369a8abd0.png)
![launch-image 2x](https://cloud.githubusercontent.com/assets/7061920/4291794/610f62c4-3dc7-11e4-8933-4499763677e2.png)
![launch-image 3x](https://cloud.githubusercontent.com/assets/7061920/4291792/610afd9c-3dc7-11e4-8de3-061e260b348e.png)

**Comment by ghost** [comment]
These were perfect @chrismorast, cheers!

**Comment by chrismorast** [comment]
Thanks @micpringle ! Let me know if anything else come up.
