### ISSUE TITLE
iPhone 6 and 6 Plus compatibility

### ISSUE THREAD

**Issue by ghost** [duckduckgo/ios-search-and-stories#47]
I've reviewed the app using both the 6 and 6 Plus simulators and for the most part it appears to function just fine. However, there is a weird visual anomaly when choosing a menu item from the slide-over menu, as shown in [this video](https://dl.dropboxusercontent.com/u/25376082/DDG-Issue.mov).

Would you like us to go ahead and investigate + fix this?

**Comment by nilnilnil** [comment]
Yes please.  Thanks for staying on top of this.

**Comment by ghost** [comment]
Fixed in 352a02d.
