### ISSUE TITLE
iPad Air Concerns

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#48]
I just went through ~70 issues and some of them were from users experiencing issues on the iPad Air.  It's unclear if it's just frustration with the fact it's not a universal applicaiton though.

**Comment by sreilly** [comment]
Where were these issues?  App store reviews, or submissions via the ios@duckduckgo.com address?

**Comment by sreilly** [comment]
@nilnilnil do you think this is still an issue?
