### ISSUE TITLE
crazy visual stuff in list view when returning to stories feed

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#5]
user report:

```
Incase they have trouble with the bug in their app that I mentioned here is a little more data:

It occurs regularly (but not always)  when returning to the story list after reading a story. 

Here is a screen shot of sort of what it looks like when it happens (all photos go away and the screen flickers) in the 2nd screen you can see  sort of the middle of a flicker. 
```

![ios_crazy_artifact](https://f.cloud.github.com/assets/347240/2081536/0374ed5c-8de4-11e3-9411-8360d2d062e0.PNG)
![ios_crazy_artifact2](https://f.cloud.github.com/assets/347240/2081535/0374c688-8de4-11e3-8b5f-f0d12c5b0bad.png)

**Comment by nilnilnil** [comment]
@micpringle @infinitekind this one is high priority at the moment.

**Comment by infinitekind** [comment]
We're on it.  I just pushed a build to testflight that may help a bit.  We'll spend more time on it in the morning.

**Comment by nilnilnil** [comment]
:fist:

**Comment by ghost** [comment]
@nilnilnil 

I think I've now been able to reliably recreate this issue. 

Could you take a look at [this video](https://dl.dropboxusercontent.com/u/25376082/DDG.m4v) and confirm whether or not it is the same thing?

You'll notice the flicker happens twice; once about half way through, and once at the very end.

-Mic

**Comment by nilnilnil** [comment]
@micpringle I've seen it happen more when returning to the home view from the stories; but perhaps it's the same artifact.  When I get it, it's sustained and just jitters flickering and can't scroll etc.

**Comment by ghost** [comment]
@nilnilnil 

Could you please give the latest build available on TestFlight a shot, and see whether or not you still experience this issue?

-Mic

**Comment by ghost** [comment]
@nilnilnil 

Did you get a chance to try out the latest build and see if this issue still occurs?

-Mic

**Comment by nilnilnil** [comment]
@micpringle the one from the 13th?  TF reporting no compatible builds with my phone.

**Comment by ghost** [comment]
@nilnilnil Yeah. I'll ask Sean to look into it.

**Comment by ghost** [comment]
@nilnilnil 

Sean has now fixed the provisioning issue on TestFlight, so you should be able to download the build.

**Comment by nilnilnil** [comment]
I've been using it without any problems for about 12 hours. I will let you know if I see anything. Also is the blur different?

**Comment by ghost** [comment]
@nilnilnil 

I've just pushed a build that fixes the blur. Check TF in a few minutes.
