### ISSUE TITLE
Swiping back returns to Home and not Results

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/ios-search-and-stories#50]
clicking a results and then swiping back returns to Home instead of the results page

**Comment by sreilly** [comment]
This was because we haven't had enough control over the UIWebView to get a snapshot of the previous page and perform the transition back to it.  I'll check into whether more recent updates to iOS might allow that.  In the meantime, the back button should work as you expect.  I know that because the back button is further away than ever on the iPhone 6/+ this becomes a more important issue.

**Comment by zekiel** [comment]
thx @sreilly  this is via @anothernewphone

**Comment by edgesince84** [comment]
The screen size is definitely making it more of a pain than anything else. Back button is fine, but I instinctively swipe back a lot, with no way to quickly return to what I was searching, either.

**Comment by nilnilnil** [comment]
This sounds like we want a real layers implementation in our app. Based on my understanding, that is a lot of work.

**Comment by apbendi** [comment]
This functionality is built into the `WKWebView` class introduced in iOS 8, so if you are planning to switch from `UIWebView` this would be a [one liner](https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKWebView_Ref/index.html#//apple_ref/occ/instp/WKWebView/allowsBackForwardNavigationGestures).

**Comment by sreilly** [comment]
That would be pretty easy, but I'm not sure it's a worthwhile tradeoff to gain that feature but lose the ~30% of devices that are still running iOS7.

**Comment by apbendi** [comment]
Yep, agreed. But if it's on the roadmap, it might not be worth implementing a complex solution to make this worth with UIWebView either.

**Comment by sreilly** [comment]
We could do this pretty easily now if we were OK with dropping support for iOS7.  What do you all think?  @thm @nilnilnil @chrismorast
