### ISSUE TITLE
Empty gap where device status bar would be in landscape view

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#54]
The space is there but we don't show anything in it. Can we just shorten the height of the frame to accommodate only the height of the search field?
![img_4632](https://cloud.githubusercontent.com/assets/7061920/6691443/d2b4ccc0-cc83-11e4-81ec-874aa52cca12.png)

**Comment by chrismorast** [comment]
cc @nilnilnil , @sreilly

**Comment by sreilly** [comment]
this is resolved in the 2015 preview
