### ISSUE TITLE
Added functionality for icons

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#58]
The tabbar icons (search, stories, favorites, recents, settings) currently open the corresponding page. However, when you tap them again, nothing happens. When you tap the icon of a page you're already on, the page should scroll to the top of the main page (same effect as when you're tapping the statusbar).

_Some apps that are doing this right are Instagram, Twitter, Facebook, etc. Scroll down your feed and tap the icon of the page you're already on._

**Comment by sreilly** [comment]
all set!

**Comment by thm** [comment]
Awesome, feels so much smoother right away!

**Comment by thm** [comment]
@sreilly Looks like we forgot to apply this to the Settings tab. Can you also make sure that when you're on a sub-page (eg. Sources, Readability, Region) you go back up the to the main page (Settings)?

**Comment by thm** [comment]
@sreilly I noticed tapping the Settings icon makes the page go up a level to the main Settings page now, awesome! Feel free to mark this task complete once the icon also makes the Settings page scroll to the top!
