### ISSUE TITLE
Remove stories from search, and missing dividers

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#59]
Recently read stories are appearing within search. We should only have recent searches appear within search. Recent stories should only appear within the recent stories tab (which is already the case).

In addition, I'm missing a lot of dividers throughout the interface, can you add them back in?

![photo-31-08-15-3-12-13-pm](https://cloud.githubusercontent.com/assets/1379822/9579586/1b2778f6-4ff4-11e5-9a24-afe98e6f3626.png)

More missing dividers:
![photo 31-08-15 3 12 20 pm](https://cloud.githubusercontent.com/assets/1379822/9579596/24989550-4ff4-11e5-805e-4453fe5ae3eb.png)

**Comment by sreilly** [comment]
the dividers should be back now, but still have to filter out the stories

**Comment by sreilly** [comment]
as of the latest commit (testflight forthcoming) the stories are no longer listed in the recent query list

**Comment by thm** [comment]
@sreilly I'm still seeing URLs that I've surely not typed in myself. Only search queries should be visible here and also on the Recent Searches tab.

Can you also make sure that whenever there's a long query it'll be truncated with the three dots right before the plus icon? (instead of behind the icon)
![photo 03-09-15 1 41 16 pm](https://cloud.githubusercontent.com/assets/1379822/9657480/c0395f68-5241-11e5-9e00-b637e95792d2.png)

**Comment by sreilly** [comment]
Hi @thm, that is strange.  Could you clear your history in order to make sure that some story items aren't appearing in there?  Or maybe you did clear your history and that's what caused the item to be disassociated with a story?

The ... truncation has been fixed for the next update.

**Comment by thm** [comment]
@sreilly it looks like this happens when you open a story from the feed, focus the search-field and then hit search. So I guess that makes sense, but maybe it's not ideal to have full URLs pop up on recents. We don't do this in the Android app either. Can you exclude those refresh-searches from recents?

How to reproduce:
1. Open a story
2. Tap search-field
3. Tap "Search"
4. Story URL appears in recents

**Comment by sreilly** [comment]
ok, this should be fixed in the just-pushed build.  If you have some of these items left they may still appear in your recents list but not the search view.  Anytime you manually enter a URL or follow your steps above, those raw URLs won't be entered into your history.
