### ISSUE TITLE
sometimes our custom "layers" are broken

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#6]
and the user can't go back.  This additionally has issues where the wrong icon (back vs. hamburger) is being shown.

**Comment by ghost** [comment]
@nilnilnil 

Are you able to provide some screenshots, or even better a video of this happening? 

If not, could you please provide the steps necessary to recreate.

**Comment by nilnilnil** [comment]
It often happens when hitting the home button while rotating to landscape.
