### ISSUE TITLE
Fix share topbar and message format

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#60]
When sharing a story the topbar looks horrible, Can you use the default color and alignment treatment here? That would be white text on a fully red topbar.

![photo-31-08-15-2-46-18-pm](https://cloud.githubusercontent.com/assets/1379822/9579967/922a20dc-4ff6-11e5-80d8-bf4dd199b70c.png)
![photo 31-08-15 2 46 29 pm](https://cloud.githubusercontent.com/assets/1379822/9579729/fc13cf68-4ff4-11e5-8be6-db7b5427991d.png)

**Comment by sreilly** [comment]
This has been fixed for build 600

**Comment by thm** [comment]
Some points of feedback:

![feedback](https://cloud.githubusercontent.com/assets/1379822/9716504/a494099e-556a-11e5-9cce-06c7997b2c0d.png)

**Comment by thm** [comment]
If it turns out to be impossible to use Proxima Nova here and a white statusbar, then perhaps it would be better to simply go with the default iOS treatment (blue Helvetica links on white background) rather than putting a lot of hours into figuring out a workaround. All I'm interested in is consistency, whether it's within iOS or within our own branding

**Comment by sreilly** [comment]
I've just pushed an update (build 606) which reverts to the light background in the navigation and status bars.  It does use the "duck red" for the button title foreground colour though, to retain a bit of the DDG branding, fit with iOS, and also... work.

As for the URL position, please see my message above which explains a bit about why embedding the URL in the text doesn't work for several of the sharing methods.  Would be happy to discuss it in real-time via Skype or something if that wasn't clear.

**Comment by thm** [comment]
@sreilly can you please make the links blue and the title dark again like the defaults within iOS are? I'd like to either go DDG or default, something in between just doesn't really feel consistent with anything to me.

The fact that we can't embed the URL in the message seems tolerable then. However, is there any way we can prevent the double-URL-situation?

**Comment by sreilly** [comment]
@thm Yes, the double-URL situation should already be resolved in recent testflight builds.  I've just pushed another update (that'll be on testflight soonish) that reverts to the default sharing header colours.

**Comment by thm** [comment]
:+1:
