### ISSUE TITLE
Settings page fixes

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#62]
1. Can you put the "Reset to Default" and "Suggest a Source" together in the "Options" section on the Settings > Sources page? and then please confirm the bottom of that page has proper spacing (should be the same as inbetween sections)
2. Can you make sure the search-field placeholder and icon are center-aligned correctly on the Settings > Sources page? and then when you focus the field, we can remove the settings icon as we've essentially arrived on a different page.
3. Can you make sure secondary labels have the same font-size as the primary labels within sections, and also make sure they're properly vertically aligned? "France" in the screenshot below:
   ![photo-31-08-15-3-52-38-pm](https://cloud.githubusercontent.com/assets/1379822/9580626/de423ca8-4ffa-11e5-886b-501c77a92c79.png)
4. For the app's version number at the bottom of the Settings page can you
   — improve the spacing above and below so it matches the section titles' spacing
   — change the font-size so it matches the section titles on the same page
   — change the text-color to #999 or rgba(153,153,153,1)
   — change "DuckDuckGo" to "Version"
   ![comparison](https://cloud.githubusercontent.com/assets/1379822/9580514/4c475c98-4ffa-11e5-8ebd-48421a340dd2.png)
   Left: current (lots of redundant space), right: new

**Comment by thm** [comment]
and 5. Can you decrease the space left of the source titles/descriptions so that the space left and right of the source icons are equal?

**Comment by sreilly** [comment]
ok, the next build includes all of these, although I'm not sure about #2 because the settings screen uses the same top bar as the rest of the tabs.  Is that supposed to be different, or was it misbehaving?

**Comment by thm** [comment]
Thanks!

in regards to point 2, I meant the Sources page. In the screenshot below you can see how the placeholder there is not centered correctly:
![misaligned](https://cloud.githubusercontent.com/assets/1379822/9612615/e5d18cb6-50e6-11e5-9a27-d133e72c2864.png)

...and in addition, we can hide the settings icon once you start searching, since tapping "Cancel" will take you back to settings:
![screenshot](https://cloud.githubusercontent.com/assets/1379822/9612765/b1aa21fe-50e7-11e5-9390-3a25e58e84e0.png)

**Comment by thm** [comment]
number 4 is nearly spot on, the only thing is that the spacing at the bottom is slightly off (comparison below, desired height is 128px/64pt)
![comparison](https://cloud.githubusercontent.com/assets/1379822/9612697/5da28bbe-50e7-11e5-9729-199ba8822da1.png)

**Comment by sreilly** [comment]
this should be set in the latest testflight build!

**Comment by thm** [comment]
#2 is not fixed yet. the search placeholder on the Sources page is not center-aligned correctly, and the settings icon is still there when you focus the search-field. The rest looks good!

**Comment by sreilly** [comment]
The placeholder alignment is centered on the entire top bar rather than the field itself.  This prevents it from jumping around when the buttons animate in/out from either side.  But if we remove the left button icon whenever the search field is active, that would resolve the problem, wouldn't it?  Now, removing that left button when the search field is active would also apply to all of the other views.  Is that acceptable?

**Comment by thm** [comment]
I don't think that would work. When you're in the browser or in `Settings > Sources` for example, we're showing the house-icon or settings-icon. Both serve a different purpose than the "Cancel" button does. Here's a quick prototype of what I initially envisioned the transitions to be: http://cl.ly/2D1C2b3V1Y1T/prototype-3.mov

**Comment by thm** [comment]
Another bug I'm experiencing there is:
1. Tap Settings tab, then go to Sources
2. Focus search-field
3. Tap Settings icon on upper left
4. Result: bang icon remains visible

Then, right-after, another bug:
1. Focus search-field
2. Result: Cancel button doesn't appear (so, there's no way of getting out)

**Comment by thm** [comment]
@sreilly I noticed you removed the settings icon when on the `Settings > Sources` page and searching. I actually quite like it, feels a lot simpler. Let's keep it this way!

Although, searching doesn't work yet. After entering a query and hitting "Search" I'm taken to this page with a blank search-field:
![photo 10-09-15 7 07 27 pm](https://cloud.githubusercontent.com/assets/1379822/9795266/e5139174-57ef-11e5-9326-1e16058393e1.png)
