### ISSUE TITLE
Math for screen height is off in stories and web pages

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#64]
The screen height doesn't seem to be calculated correctly.

Here are some screenshots.
1. When I click a story this is how the screen slides in. Notice the black bar at the bottom which seems to be the offset once the screen loads.
   ![img_5081](https://cloud.githubusercontent.com/assets/7061920/9586517/25197fde-4fd2-11e5-8086-07dcf1382b5a.png)
2. When I view the image detail pane, it gets cut short and you can see the image grid and tab bar underneath it. 
   ![img_5079](https://cloud.githubusercontent.com/assets/7061920/9586539/4ed2aeb8-4fd2-11e5-9b37-3958c683c4c5.png)
3. When websites have items that nest to the bottom (like sharing options or in this case a message) they are not nested to the bottom but pushed partway up the screen (about the same added space that the black bar in the earlier screenshot takes up)

![img_5083](https://cloud.githubusercontent.com/assets/7061920/9586561/69951e2a-4fd2-11e5-938a-2ef19ded748c.png)

**Comment by chrismorast** [comment]
cc @thm

**Comment by sreilly** [comment]
all fixed!
