### ISSUE TITLE
Put homepage option back in settings

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#65]
If I'm right, we used to have a homepage option (like we have on Android) so that you can set your homepage to be Stories, Favorites, Recents or just Search. @sreilly, can you put this option back?

cc @chrismorast

**Comment by sreilly** [comment]
Sure thing.  Although what do you think about simply returning to the last used tab?

**Comment by thm** [comment]
@sreilly I'm concerned people may perceive that as an inconsistency. Ofcourse, when you only minimize the app, and then open it again, the app will just continue with what you were doing. However, the homepage is the page you see when you first open the app (currently the story feed)

**Comment by sreilly** [comment]
completed as of this morning's testflight build!

**Comment by thm** [comment]
Thanks, can you make the structure more like what we have on Android?:
1. Rename the section from "Home" to "General"
2. Make the Homepage option a separate menu (like the Sources and Region options)
3. Rename the search option from "Search Only" to "Search"
4. Rename "Stories" to "Stories (Default)"
5. Make sure that the currently selected option shows on the right (similar to Region option)
—
6. While you're at it, can you add an "s" to the "Save Recent" option on the Settings page? :smiley:

**Comment by sreilly** [comment]
All set.  The requested changes are in build 614!

**Comment by thm** [comment]
Don't forget about number 6! Also, the "Stories" option appears as "Stories" instead of "Stories (Default)" on the Settings page

**Comment by sreilly** [comment]
Oops, I read number 6 wrong.  Also changed the detail label for the selected home page option. All set now! (as of the next auto-build)

**Comment by thm** [comment]
@sreilly awesome, thanks!
