### ISSUE TITLE
Auto-hide topbar and tabbar when scrolling in Search

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#66]
Just like Safari on iOS, can we automatically hide the option-bar at the bottom of Search when you start scrolling the page, and then bring it back once you scroll back up a bit? We can use the same transition as Safari uses

_Note: this is just for the Search tabbar (prev, next, favorite, share), not for the main tabbar_

**Comment by sreilly** [comment]
@thm to clarify, that toolbar is also used when you navigate into search results.  So it should auto-hide even when viewing normal web pages?

**Comment by thm** [comment]
Yes, it should auto-hide when you start scrolling everywhere within Search. Whenever you open a new page (so, navigating the web) it should pop back up until you start scrolling again. Take a look at Safari for the desired effect.

**Comment by sreilly** [comment]
Cool.  Just implemented this and it should be on hockey now, and hopefully testflight soon!

**Comment by thm** [comment]
Can you make the tabbar appear again after tapping the general area of where the tabbar would be? (similar to Safari)

**Comment by sreilly** [comment]
Sure!  It should now show the toolbar (and reject other effects of the tap) if it detects a tap in the toolbar-area.

**Comment by thm** [comment]
@sreilly tapping in that area makes the tabbar appear now, but it still activates the element behind. In addition, horizontal scrollbars seem to appear in the middle of the screen now, can you move those down?
![photo 27-09-15 2 49 32 pm](https://cloud.githubusercontent.com/assets/1379822/10125044/e2078d8a-6566-11e5-8b1c-3d7387d27b13.png)

**Comment by sreilly** [comment]
@thm the scrollbar thing is now fixed, but the tap interception is a bit of a problem.  I'll take a different approach and this will be done a bit later tonight.

**Comment by thm** [comment]
@sreilly In addition, can you make the tabbar re-appear after scrolling up about 50px rather than immediately? That should stop it from jumping up and down when scrolling very small distances. I think having the tabbar disappear when scrolling _down_ could be immediate like it is now, but I would be curious to see the above change live to make the final call on that. Thanks!

**Comment by sreilly** [comment]
@thm done!

**Comment by thm** [comment]
@sreilly is a build brewing? because in the latest build links are still activated behind the tabbar

**Comment by sreilly** [comment]
no new builds are brewing yet.  It was a hack to implement though, so I wonder if it's simply not working properly.  Do you know if the links you've clicked invoke javascript or if they are "normal" links?

**Comment by thm** [comment]
@sreilly just normal links as far as I know. I've tested it on a DDG search-results page, and on a Wikipedia article so far.

**Comment by sreilly** [comment]
ok, I've got a much better fix now.  Will try to tweak the long-press-on-an-image handler a bit more and then push another update

**Comment by thm** [comment]
@sreilly This looks fixed in the latest build, thanks! I take it you're changing the web view's height when transitioning in the tabbar? is there any way we can give the web view a transition too? If a website has an element fixed to the bottom of the page it currently jumps 80px up to make way for the tabbar, but it would be nice to have that go smoothly. Not mandatory, but if it's an easy fix(?)

**Comment by sreilly** [comment]
@thm I'm 99% sure that there's no way to make any html/css elements that are pinned to the bottom of the page smoothly animate with the toolbar.  When the tab bar is hidden or shown we aren't changing the size of the webview, but rather setting a guide that tells the webview that the viewport (content view) inset has changed.  The webview internally tells the web page that that viewport has changed, but I don't think it's feasible to send that notification continuously as the animation happens.  Even now, we don't send that notification - it's a function that's built-in and handled by the web view's scroll pane.

As for the top header bar auto-hiding, I think that should be pretty easy.  Can we just have it show and hide at the same times as the bottom bar?

**Comment by thm** [comment]
@sreilly alright, then don't worry about it! Do we have a task for the topbar auto-hiding yet? otherwise, yes it can animate at the same time as the tabbar.

**Comment by SwiftlyDeft** [comment]
@thm This feature has been added, could you look over it, in the next build. Thank you

**Comment by thm** [comment]
@SwiftlyDeft In the latest build (v743) I'm not yet able to get the topbar to hide on-scroll. The topbar should hide simultaneously with the tabbar. Ideally the statusbar should remain. Please note, this only applies to the webview. On the Stories/Favorites/Recents-pages we should keep all bars visible like we already do. Please let me know if anything is unclear!

![detail](https://cloud.githubusercontent.com/assets/1379822/12615786/10c7c530-c508-11e5-8aa2-10159a7f2da2.png)

**Comment by SwiftlyDeft** [comment]
@thm Got it. Can you have a play with the latest version of the app. Now this is just the first step where the Navigation Bar gets hidden (like the bottom tool bar). It does not animate out like safari does but it's a start. Please note it still shows a label (address) and around 20pt below the status bar. Let me know what you would like as we can easily remove the show navigation bar and just show the status bar now as changes have been made to accomodate this. Thank you

**Comment by thm** [comment]
@SwiftlyDeft excuse the late reply. I couldn't get this to work, but have been able to now. I think this looks awesome, keeping the domain in the topbar is a great idea. Some minor feedback:
1. Can you move the domain that is in the minified topbar up 3pt so it's vertically centered? (in the comp below the title has been moved 6px@2x)
   ![comparison](https://cloud.githubusercontent.com/assets/1379822/13145256/b35e7700-d64f-11e5-8980-5ae52c3c2d5c.png)
2. When searching, the query doesn't appear in the minified topbar. The topbar is minified, but remains empty. Can you make sure the query shows up in there?
3. I noticed this bug where the search-field's placeholder is visible while the query is also in the search-field. This happens when opening a story, after a few seconds the placeholder is gone:
   ![double-text](https://cloud.githubusercontent.com/assets/1379822/13145259/b656fa54-d64f-11e5-9621-3f9ed2edcf8b.png)

**Comment by SwiftlyDeft** [comment]
@thm: #1 has been fixed, it's got the right spacing now. 
![updated](https://cloud.githubusercontent.com/assets/4774399/13208628/a586fb74-d97f-11e5-9450-22f394fe9fcd.png)

**Comment by SwiftlyDeft** [comment]
@thm, Have a play with the latest build, these issues should be resolved.
