### ISSUE TITLE
Alignment issue in search field

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#67]
@sreilly can you make sure the margin on the right of these two icons is similar to the space above and below the icon? That means moving the icon to the left about 7px/3.5pt

![comparison](https://cloud.githubusercontent.com/assets/1379822/9609303/46f42ec2-50d3-11e5-9835-f27f41a4e362.png)

**Comment by sreilly** [comment]
should be fixed now, but please double-check!

**Comment by thm** [comment]
Yup, looks good!
