### ISSUE TITLE
More alignment issues

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#69]
1. The distance of the 3-dot menu to the edge of the screen is 16px, while the distance of the search-field (and the segemented tabbar) to the edge of the screen is 20px/10pt. Can you decrease the margin on both sides of the latter so it matches the margin of the 3-dot menu?
2. The refresh icon in the search field should only be visible when there's actually a URL or query to refresh
3. Upon closer inspection I think we should have the labels in the segmented tabbar be the same text-size as the search-field placeholder. So that means decreasing the font-size by 2px/1pt to 28px/14pt

![more-bugs](https://cloud.githubusercontent.com/assets/1379822/9610089/a5c2e94e-50d7-11e5-8701-56906a850633.jpg)

**Comment by sreilly** [comment]
This should now be fixed (pending most recent build 596)

**Comment by thm** [comment]
@sreilly 1 looks good, but I'm still spotting 2 and 3

How to reproduce 2:
1. Tap search field
2. Tap recent search and quickly tap home icon before the page loads
3. You're taken back to Favorites/Recents but the refresh icon remains

**Comment by sreilly** [comment]
ok, both of these should now be fixed (really)
