### ISSUE TITLE
update icon

### ISSUE THREAD

**Issue by nilnilnil** [duckduckgo/ios-search-and-stories#7]

**Comment by nilnilnil** [comment]
![ddg-ios-7-icon_square](https://f.cloud.github.com/assets/347240/2313586/5607f76c-a30b-11e3-93db-28ee3e2e0ce3.png)

Is this asset sufficient to update the icon?

**Comment by sreilly** [comment]
Unfortunately we'll need something a bit larger.  Would you have that in 1024x1024?  The one attached was 120x120 which won't be accepted.

**Comment by nilnilnil** [comment]
![duckduckgo_1024x1024](https://f.cloud.github.com/assets/347240/2314998/f67bc11c-a31d-11e3-928a-c192b4c62783.png)

**Comment by ghost** [comment]
@nilnilnil I think this can be closed now, since you merged the PR (_it seems I don't have permission to close issues_)
