### ISSUE TITLE
Greyed out story titles

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#71]
Story titles in the story feed should only be greyed out when that story is actually in the Recents feed. Removing a story from your Recents should result in the story title getting the default/darker color again

**Comment by sreilly** [comment]
ok, this is now fixed.  For these tickets would you like me to close them when I fix them or would you do it when you confirm the fix?

**Comment by thm** [comment]
@sreilly Awesome! feel free to reassign back so the creator of an issue can confirm the fix! This is not included in the latest build yet, right?

**Comment by thm** [comment]
Thanks!
