### ISSUE TITLE
Buggy behavior on 'Search' tab

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#72]
When I go to the search tab, focus the search field, and then try to click on one of the items in the list, it tries to load but nothing shows up. From there, I get different issues come up each time and I continue to click around. Sometimes it will just get stuck altogether.

**Comment by sreilly** [comment]
I'm not seeing this.  Can you try it after a force-quit to see if it happens when first started or if there's something happening in the middle that's causing things to be gummed up?

**Comment by thm** [comment]
This is happening for me too, the screenshot below is after tapping the "dribbble" favorite. However, so far I'm unable to reproduce other issues @chrismorast 
![photo 02-09-15 11 18 37 am](https://cloud.githubusercontent.com/assets/1379822/9627622/8a0464a6-5165-11e5-9519-b17003ddf171.png)

**Comment by chrismorast** [comment]
I force quit and still have the same issues. The other issues relate to the recent story feed in the search tab. Since those shouldn't be there in the first place, maybe it's not worth looking into. But incase this relates to something bigger, here's what you can try in hopes of reproducing it;

First, try reading several stories from different sources so they populate the recent story feed.

Then do this:
Click on search tab > Focus field > select a recent search (it loads but the screen doesn't change > now click on one of the recent stories. Occasionally it will load the story but most of the time it does something buggy. Once it crashed the app, a couple times it closed the keyboard and just showed a blank gray screen with the search field (populated with the recent search I had clicked on) home button and web controls at the bottom.

**Comment by sreilly** [comment]
ok, I think I've found and fixed this bug.  The cause was that the autocompletion list wasn't being dismissed/hidden after a favorite item was tapped.  The browser would load, but everything would be behind the autocompletion view so it seemed like nothing at all was happening.

**Comment by chrismorast** [comment]
Thanks Sean, seems to be corrected now.
