### ISSUE TITLE
'Search' tab should not have recent stories in the list. 

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#73]
This should only display searches; recent and favorited

**Comment by thm** [comment]
Also mentioned in #59 ;)

**Comment by sreilly** [comment]
all fixed now.  build forthcoming!

**Comment by chrismorast** [comment]
LGTM!

**Comment by thm** [comment]
Closing this issue, but leaving #59 open for the URLs that are still appearing!
