### ISSUE TITLE
Preload screen assets

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#77]
@sreilly here are the updated assets for the preload screen: [Download ZIP](http://cl.ly/070t1y112b1h/Archive%202015-09-03%20at%205.55.03%20PM.zip)

When implementing can you make sure the logo is centered based on the entire screen (including the statusbar), and that the background-color is set to #e37151 / rgba(227,113,81,1)

Here's the design:
![0_preload](https://cloud.githubusercontent.com/assets/1379822/9663510/20f84814-5265-11e5-8b30-e1855beea936.png)

**Comment by sreilly** [comment]
great!  This is finished and will be in build 610, available shortly
