### ISSUE TITLE
iPad version is locked in landscape mode

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#78]
It does not rotate to portrait mode.

**Comment by thm** [comment]
@chrismorast works fine here, did you forget to unlock screen-rotation from the settings panel (swipe up from bottom)? did you try restarting the app?

**Comment by chrismorast** [comment]
I rechecked this and it occasionally rotated but stopped. Attaching screenshot. As you can see, the device status bar is rotated but the app is not.

![img_0386](https://cloud.githubusercontent.com/assets/7061920/9695082/449a5a38-5313-11e5-8f25-53be5baf5e1b.PNG)
![img_0387](https://cloud.githubusercontent.com/assets/7061920/9695084/4a68157c-5313-11e5-81f7-2fe5ae73c6b7.PNG)

**Comment by sreilly** [comment]
@chrismorast can you reliably reproduce this?  I haven't been able to get it to occur on an iPad mini running iOS 8.4.1.  Are you running the iOS 9 beta or maybe an older version of iOS8?

**Comment by chrismorast** [comment]
Yes, I can reproduce every time. I'm running 8.1.1

**Comment by sreilly** [comment]
Can you update to 8.4 and see if it occurs there? I'm not 100% sure but I believe every iPad that runs 8.1 should also handle 8.4.

On 9 September 2015 17:42:42 BST, chrismorast notifications@github.com wrote:Yes, I can reproduce every time. I'm running 8.1.1  —Reply to this email directly or view it on GitHub.

**Comment by nilnilnil** [comment]
Do we have an idea of what our installed iOS base looks like? Is requiring 8.4 a mistake?

**Comment by sreilly** [comment]
You can get some info about installs for each version of iOS in the new iTunes app analytics, but I don't have access to that.

However, I wouldn't recommend requiring iOS 8.4.  I just suspect that this may be an iOS bug that was fixed between 8.1 and 8.4.

**Comment by nilnilnil** [comment]
Agreed! I was more speaking to the upgrade to 8.4 being the solution. Maybe I'm confused.

**Comment by chrismorast** [comment]
But the issue is that anyone running 8.1 will see what I'm seeing. That's what I'd like to fix if possible.

**Comment by sreilly** [comment]
@chrismorast Yes, but if the bug is in iOS 8.1 then it's possible that there's nothing we can do about it.  However, I've just pushed a change (build 612) which _might_ fix it, but I don't have an 8.1 device to test on.  Could you give it a whirl and let me know if it's any better?

**Comment by chrismorast** [comment]
Nice work @sreilly ! It is corrected in build 612
