### ISSUE TITLE
Empty states

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#79]
1. Can you increase the line-height of the description by 6px/3pt pixels? ("Add stories to your fav...")
2. Can you move the description up about 20px/10pt?
3. Can you make sure the background is #eee like everywhere else in the app
4. Can you increase the font-size of the title by 4px/2pt to 44px/22pt ("No Favorites", "No Recents")

Left: current, right: as designed
![comparison](https://cloud.githubusercontent.com/assets/1379822/9663776/6e506410-5266-11e5-8b17-1ddd3215bf8e.png)

**Comment by sreilly** [comment]
These changes are applied in build 615!
