### ISSUE TITLE
Consistent font sizes

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#80]
The font-size of the list items on the Settings page are perfect, can you decrease the font-size of the list items on the Favorites and Recents pages so they match those of the Settings page? Same goes for Search and autocomplete!

**Comment by sreilly** [comment]
The next build (603) makes the font size consistent for all of these items (Proxima Nova 17pt).

**Comment by thm** [comment]
Thanks, this looks so much better. Can you also make sure we're consistently using the same color for text? The text on all pages but the Settings page seems to be too dark, can you confirm all text including the Settings page is #222 / rgba(34,34,34,1)

**Comment by sreilly** [comment]
ok, all text should now be #222222.  The settings text was actually a different value before, but it should all now be consistent.  The secondary text for any list items now uses the same value as the old settings row detail text: red:137.0f/255.0f green:137.0f/255.0f blue:137.0f/255.0f (aka #898989).
