### ISSUE TITLE
Refresh icon is in front of feed

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#82]
@sreilly can you make sure the refresh/loading icon is behind the feed so that it doesn't cover stories in the feed?

**Comment by sreilly** [comment]
this may be a tricky one.  I don't see any API for controlling the position or size of the refresh indicator, but will check into it once the bugs are resolved

**Comment by thm** [comment]
:+1:

**Comment by thm** [comment]
In addition, can you also change the loader's color from #575f6c to #aaa / rgba(170,170,170,1)?

**Comment by sreilly** [comment]
done, thanks! (build coming shortly)

**Comment by thm** [comment]
@sreilly This doesn't seem to be fixed in the latest build yet(?)

**Comment by sreilly** [comment]
Hi @thm we are setting the specified tint colour on the refresh control but it seems to be more of a hint than a setting of the exact colour.  I'll continue to look for a way to get the exact colour we specify to stick, but I think our options are currently to either a) accept the (darkening) adjustment that is being applied by the system, b) lighten our colour setting to compensate for the darkening, or c) just keep digging to figure out why the exact colours aren't being accepted.  I'll work on the other remaining items in the meantime :)

**Comment by thm** [comment]
@sreilly option B sounds good to me then. My only problem with the current loader is that it's so prominent (in terms of color), in addition to it appearing in front of the first story at times.

**Comment by SwiftlyDeft** [comment]
@thm Could you check on the latest build and let me know if this is ok for you now?

**Comment by thm** [comment]
@SwiftlyDeft thanks, this is perfect!
