### ISSUE TITLE
Some story images not displaying until scroll

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#84]
Sometimes I click on the story icon to go back-to-top of the story feed, there are some new stories with images that don't load. Then when I go to scroll they suddenly appear.

**Comment by sreilly** [comment]
@chrismorast I believe this is now fixed for build 608.  Can you check once it pops through in testflight?

**Comment by thm** [comment]
Marking complete as this seems to be fixed! cc @chrismorast

**Comment by chrismorast** [comment]
lgtm!
