### ISSUE TITLE
Optimized mosaic view for iPad

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#86]
The story titles of large stories are twice the height of those of small stories so that all cover images on the page can have the same aspect ratio. The font-size of large titles is 52px/26pt

![2_stories_a](https://cloud.githubusercontent.com/assets/1379822/9759729/900bbfa4-56ef-11e5-9811-f3bd4614cded.jpg)

**Comment by sreilly** [comment]
If you like we can adjust the relative widths of the images so that they have the same aspect ratio and still keep the title bars the same size.  Would that be preferable @thm?

**Comment by thm** [comment]
No, I like it with the larger titles, it's just a heads up after seeing the current implementation!

**Comment by sreilly** [comment]
@thm I'm a bit confused about what's happening here.  In the mockup the large and small images don't have the same aspect ratio.  The large ones are 2:1 and the small ones are about 2.064516129:1.  The large title bars are also not twice the height of the small ones.  Maybe I'm mis-measuring?  I can make them have the aspect ratio if you like - it actually makes it easier to implement.  For the title bar height, should I use the smaller ones in the mockup as a reference point and make the larger panels fill a proportional amount of space?  So, I guess what I'm asking is whether I should make all of the images use the same 2:1 aspect ratio or use a different algorithm that I'm not able to discern from the mockup?

**Comment by sreilly** [comment]
@thm ok I've just pushed a build which I believe addresses all of these issues.  It has the larger titles, a slight translucent white edge along the bottom of the story images, and uses a 2:1 aspect ratio for all of the images in "mosaic mode".  The title bar height for the large stories is fixed at 118pt, and the smaller title heights will fill the remaining space after those images are sized at the same 2:1 ratio.  Should be on hockey in a few minutes!

**Comment by thm** [comment]
@sreilly I'm sorry, looks like I haven't been notified about your previous comment! Using the same aspect-ratio for all images is what I was after, yes! I think this is near-perfect. Here are some small points of feedback:
1. Can you _decrease_ the font-size of large titles from 26pt to 24pt? I think it's slightly too large after having been able to review it live
2. In addition, can you slightly _increase_ the font-size of the stories' category-tag. Maybe only by 1-2pt, it looks slightly too small, especially on mobile.
3. Is it possible to have the active tabbar icon remain its original color when the share-popup is active? [see screenshot below]
4. Is it possible to have the share-popup fixed at the bottom of the screen like we have on iPhone? (without an arrow pointing somewhere) Or, even better, can we have it point to the 3-dot icon properly? [see screenshot below]

![two-issues](https://cloud.githubusercontent.com/assets/1379822/10146175/ac670edc-6627-11e5-9d7e-9a76a8428da2.jpg)

**Comment by sreilly** [comment]
@thm just fixed all of the above.  Should be a build on hockey in a minute or two!

**Comment by thm** [comment]
@sreilly nice, looks good
