### ISSUE TITLE
Optimized topbar for iPad

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#87]
@sreilly can you make sure that on iPad the search-field and segmented tabs have a maximum width of 710px/355pt. The dropdown is slightly wider at 750px/375pt (same width as an iPhone 6 screen). In terms of measurements we're trying to mimic the measurements on iPhone here, so the home/settings icon would appear in the same place. This means that the search-field gets slightly less wide to make place for the house/settings icon and the "Cancel" button on either side.

![1_search](https://cloud.githubusercontent.com/assets/1379822/9759834/4bee0902-56f0-11e5-8c19-18f70befbe3f.png)

**Comment by sreilly** [comment]
@thm question: where should the cancel button go when the field has the focus?  If it should be next to the field, should it animate in all the way from the side of the screen?

Also, what about the home button when the user is more than one level deep: where should that go, and how should the animation go?

**Comment by thm** [comment]
@sreilly Can you make it fade in while it slides in with the changing width of the search field?

Quick demo here: http://cl.ly/0v3J3r0N3o0M/iPad.mov

**Comment by sreilly** [comment]
will do!

**Comment by sreilly** [comment]
@thm the latest build includes the search field that works closer to what you describe here, aside from the popover.  One problem is that on the iPhone 6+ 355 pts isn't wide enough to fill the top nav bar, so I set it to a maximum of 414pts.  Is that ok?

Also, for the popover, would you like to have the default iOS behaviour of taps outside of the popover dismissing it, or should it stay visible whenever the search field is active, as on the iPhone?

**Comment by thm** [comment]
Yup, a tap outside should dismiss the popover, so the same result as the Cancel button I think! Also make sure the popover overlays the current page. So, when you search on the Stories page for example, you'll be able to see the stories behind the popover. For the overlay let's try ~35% black for now

I'll check the 415pt search-field later today on an iPad, curious how it looks there. But it'll probably be fine!

**Comment by sreilly** [comment]
@thm when in the search tab, should that still have a popover or just use the search field contents to filter the contents of the main view (as it does on the iPhone)?

**Comment by thm** [comment]
@sreilly Good question! I think we should put everything in the popover on the Search page, for consistency. So that would look exactly like the screenshot posted above, until you start typing and auto-complete takes over

**Comment by thm** [comment]
I also noticed the Cancel button and home icon don't fade in yet, they do slide in, but ultimately they should start at 0% opacity and go to 100% opacity during the sliding animation

**Comment by thm** [comment]
I also noticed that when switching pages on the iPad the blue progress bar is briefly visible on the upper-right

**Comment by sreilly** [comment]
@thm ok, I'm just about to push an update that implements all of this.  The cancel and home button animation is in there, but it's a quick one (I believe it's 0.25 seconds).

**Comment by thm** [comment]
1. The cancel button still doesn't fade in. Again, it slides in, but it doesn't go from 0 opacity to 100 over the course of the sliding animation. It pops into view, and then slides to the left. Here's a slowed-down demo: http://cl.ly/1d3I3r3T2K2h/comparison.mov
2. You forgot to add the overlay behind the popover. Can you add an overlay of 35% black so that the popover doesn't blend in as much with the stories underneath?
   ![overlay](https://cloud.githubusercontent.com/assets/1379822/10017087/f066cd30-612b-11e5-89d6-06703a76ed54.jpg)
3. And in the image below is more alignment and visuals feedback:
   ![popover-feedback](https://cloud.githubusercontent.com/assets/1379822/10017393/327046fa-612e-11e5-9df6-64326b0cb182.jpg)

**Comment by sreilly** [comment]
This should be all fixed as of the next build!

**Comment by thm** [comment]
1. :+1: 
2. Can you make tapping the overlay dismiss the popover? So, same functionality as the "Cancel" button. Right now when you tap the overlay, it activates the story underneath
3. Do you think a better solution for the popover's arrow would be adding the same 50px margin at the top of the list as we have for iPhone?
   Current (when scrolling the list down, the white background becomes apparent):
   ![weird-background-shift](https://cloud.githubusercontent.com/assets/1379822/10078150/c636f7b0-62e3-11e5-95bf-e00cccf24cd5.png)
   Proposed:
   ![better-solution](https://cloud.githubusercontent.com/assets/1379822/10078277/364e1024-62e4-11e5-96e8-fe9de68511ca.png)

**Comment by sreilly** [comment]
@thm Personally I prefer to omit the empty grey margin at the top as it's just wasted space.  I think the current solution where the line disappears as it touches the triangle looks pretty good.

I do think that tapping to dismiss having the same effect as the cancel button (ie resetting and taking the focus away from the search field) might be a bit frustrating.  I can imagine people accidentally tapping outside of the popover (quite a large target) and being upset about losing their half-typed query.  Maybe we could simply ignore taps outside of the popover in the dimmed area?

**Comment by thm** [comment]
I don't really like the white arrow tip, in the list's resting state I like the way it looks, but when scrolling it just looks awkward. The argument for it being wasted space is less of a concern to me than it looking slightly akward with the grey space inbetween. So, below is the solution I've come up with:
![screen shot 2015-09-25 at 10 48 20 pm](https://cloud.githubusercontent.com/assets/1379822/10147823/96d07f0a-6630-11e5-8934-39e4f9117766.png)
...and then when scrolling down the list:
![screen shot 2015-09-28 at 10 33 27 pm](https://cloud.githubusercontent.com/assets/1379822/10147904/f95480b8-6630-11e5-8b42-026ab488862e.png)

Below is the final spec sheet for the visuals. In addition, can you round off the tip of the arrow with 1-2pt more? (top = current, bottom = new):
![comparison-2](https://cloud.githubusercontent.com/assets/1379822/10148265/c3708012-6632-11e5-9d47-4cd365703ad0.png)

**Comment by thm** [comment]
In addition, I think tapping the overlay should dismiss the popover. It's default/expected behavior in iOS

**Comment by sreilly** [comment]
@thm This should be done now, and the resulting build on hockey.  I think the result is a tiny bit weird because touches on the dimmed view dismiss the popover (and aren't passed through), but taps above the dimmed view don't.

Tapping the dimmed view performs the same action as the Cancel button, but do we want to clear the contents of the search field upon tapping outside the popover?

**Comment by thm** [comment]
@sreilly we should never clear the search-field unless the user taps the clear-icon. When you tap "Cancel" or the overlay the value should reset to the currently active query or URL

Also, I'm sorry for the extra work this has brought you, but can you please remove the arrow all-together and make the first item flush with the top of the popover? See screenshot below:
![screen shot 2015-10-01 at 8 24 12 pm](https://cloud.githubusercontent.com/assets/1379822/10229864/771040aa-687a-11e5-9dbb-d4f3ee977ede.png)

**Comment by thm** [comment]
Also found this on the Favorites and Recents pages. The overlay isn't stretched to the top.
![photo 01-10-15 3 47 07 pm](https://cloud.githubusercontent.com/assets/1379822/10230318/b9e7d508-687c-11e5-9979-bd1ff0bf2127.png)

**Comment by sreilly** [comment]
@thm cool... can you give the latest (in about 3 minutes) build to see how it feels?

**Comment by thm** [comment]
1. We seem to only show the 5 most recent recents and favorites in the popover. That should be the 5 most recent recents and _all_ favorites.
2. The icons' measurements are off again:
   ![icons](https://cloud.githubusercontent.com/assets/1379822/10267597/9c68b306-6a9a-11e5-92cb-c0b91d28e031.png)
3. Can you make the margin inbetween the topbar and the popover 16px/8pt again? It's currently ~3px

**Comment by sreilly** [comment]
@thm all set, thanks!  Changes made and pushed.

**Comment by thm** [comment]
@sreilly perfect, thanks! on just the Favorites and Recents pages can you make sure the distance between the popover and the search-field is 16px/8pt instead of 32px/16pt? That would make it properly cover the segmented tabbar. Though please note, only on the Favorites and the Recents pages.

_Feel free to move this to the "iteration 1" milestone if it takes up too much time!_

**Comment by sreilly** [comment]
@thm piece of cake!  this change is baking now

**Comment by thm** [comment]
@sreilly Thanks a lot!
