### ISSUE TITLE
More alignment issues

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#88]
1. The search-placeholder and the list items aren't aligned, and neither have the correct distance from the left edge of the screen
2. The padding left and right of the "Cancel" button is inconsistent.

![measurements](https://cloud.githubusercontent.com/assets/1379822/9796744/fe7f63ba-57f7-11e5-8595-b3abd820b428.png)

**Comment by sreilly** [comment]
Nice catches!  Fixed in build 616.
