### ISSUE TITLE
Progress bar visuals

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#90]
@sreilly can you update the progress bar so that it matches the one we have for Android? #98c5e7 / rgba(152,197,231,1) for the background and #4495d4 / rgba(68,149,212,1) for the foreground:

![progress-bar](https://cloud.githubusercontent.com/assets/1379822/9853787/bf687e8a-5b05-11e5-9e25-f8a27a0925c5.png)

**Comment by thm** [comment]
On both iPad and iPhone the topbar now extends below the progress bar during search. I'm reopening this issue as I assume it may be related (click image for full view):

![extended-topbar](https://cloud.githubusercontent.com/assets/1379822/9899818/a7ded2fc-5c5c-11e5-91fd-4997bd3d373f.png)

**Comment by sreilly** [comment]
@thm This actually isn't a bug... that red line comes from the top of the DDG search page html.  Maybe we should consider moving the progress bar to a different location so that it won't be confused with a misalignment when loading the search results page?

**Comment by thm** [comment]
@sreilly Oh I see! I'll check if we can potentially hide it in the front-end. In the meantime can you add a slight 1px/0.5pt shadow on the topbar? 15% #000 / rgba(0,0,0,1) so that it pops out a bit. I would prefer not to move the progress bar away from the current location

**Comment by thm** [comment]
One thing to note: I noticed the x-percentage shadow on the tabbar isn't actually translucent. I assume a 15% #000 color in iOS coding language translates to a shade of grey rather than a translucent black line?

**Comment by sreilly** [comment]
@thm We could add a shadow to the top bar, but it will need to be added independently to each of the views in the content area (web view, stories, favourites, recents, settings, etc).  Would you like it just in the web viewer or in all of the content views?

**Comment by thm** [comment]
@sreilly preferably everywhere
