### ISSUE TITLE
Increased tap-area for story-options

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#94]
@sreilly can you increase the tap-area of the story options so we can decrease the amount of misses there?

![comparison](https://cloud.githubusercontent.com/assets/1379822/9899238/d55666b8-5c58-11e5-8687-96e757c57458.png)

**Comment by SwiftlyDeft** [comment]
@thm, increased the tap-able area for the story options. Here are the actual sizes, highlighted in code.
<img width="503" alt="screen shot 2016-01-08 at 2 49 33 pm" src="https://cloud.githubusercontent.com/assets/4774399/12188201/e0c1eed2-b617-11e5-9743-7ba944ad51a6.png">

**Comment by thm** [comment]
@SwiftlyDeft awesome, thanks!
