### ISSUE TITLE
Search tabbar issues

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#96]
1. The Search tabbar still has a 2px/1pt shadow, rather than the 1px/0.5pt shadow it should have. Can you make sure both the Search tabbar and the main one have the same visual treatment? In addition, please make sure the shadow is actually a translucent color rather than a shade of grey (again, for both of the tabbars):
   ![comparison](https://cloud.githubusercontent.com/assets/1379822/9902979/d01cc3c6-5c72-11e5-9fb0-8af0b7bdca5e.png)
2. When swiping from the left-edge to go back, the tabbar stays fixated at the bottom of the screen, only to suddenly reveal the main tabbar a split-second later. Is there any way we can have the Search tabbar slide with Search? Note that this shouldn't be for every page within Search, just for transitioning between Search and any top-level page (Stories, Favorites, Recents, etc):
   ![photo 16-09-15 12 40 17 pm](https://cloud.githubusercontent.com/assets/1379822/9902787/6a335224-5c71-11e5-8651-cc767dfe0429.png)

**Comment by sreilly** [comment]
@thm I've added a transition to switch the toolbars when a content view changes, but it doesn't (yet) slide in sync with the search/web views.  That would be a bit trickier.  Please let me know if the new behaviour isn't good enough for this milestone!

**Comment by thm** [comment]
@sreilly I think the animation makes it feel unnecessarily slow. I guess we can keep it this way for now, but I would ultimately like to have both the tabbars grouped with their corresponding segments within the app. I'm moving this to the "iteration 1" milestone. However, feel free to move it back if you think it's doable in a short term!

**Comment by thm** [comment]
@sreilly marking complete, looks awesome, thanks!
