### ISSUE TITLE
Recent and Favorited story feeds don't scroll all the way to the bottom

### ISSUE THREAD

**Issue by chrismorast** [duckduckgo/ios-search-and-stories#97]
The tab bar covers part of the title of the last story in each feed. We need to add the same padding below the final story that we did for the Main story feed.

**Comment by sreilly** [comment]
Recent builds should no longer have this problem.  @thm it seems that this issue, and possibly some others, have both milestones assigned.  Is that intentional?

**Comment by thm** [comment]
@sreilly I don't think that's possible, I initially added some issues in the "iteration 1" milestone, and then moved them back to the main milestone, maybe that's causing some confusion? it's not intentional
