### ISSUE TITLE
Settings topbar features wrong icon

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#98]
The settings-icon in the topbar on `Settings > Sources` is the old icon. I don't think there are white assets yet so I'll generate those

**Comment by thm** [comment]
@sreilly the assets for the white settings-icon are added on BTS (`iOS > assets > tabbar-settings-active-dark.png`). A comparison of the current and the new icon is below:
![comparison](https://cloud.githubusercontent.com/assets/1379822/10078493/4705ed64-62e5-11e5-8040-c5f9a69de745.png)

**Comment by sreilly** [comment]
Cool.  icon updated, with a build coming soon
