### ISSUE TITLE
Remove notification popups

### ISSUE THREAD

**Issue by thm** [duckduckgo/ios-search-and-stories#99]
@sreilly can you remove these popups? I would like the story-menu to remain visible so that you can see the "Add to Favorites" label change to "Unfavorite". Same goes for the Favorites page.

![photo 18-09-15 5 09 47 pm](https://cloud.githubusercontent.com/assets/1379822/9962951/c4c66074-5e28-11e5-912d-002f1fdacde0.png)

**Comment by sreilly** [comment]
@thm We can remove the popups, but then in the favourite stories list, the story will immediately be removed from the list, which means the menu can't remain visible.  Might that be confusing?

**Comment by thm** [comment]
@sreilly I don't think that will be a problem, that would be a perfect clue that the item is removed. Ultimately we should properly transition the story out of the screen, but we can revise that later

**Comment by sreilly** [comment]
Ok, all fixed for the next TestFlight build!

**Comment by thm** [comment]
@sreilly :+1: Can you also make sure the stories don't blink when you favorite or unfavorite a story?

**Comment by thm** [comment]
@sreilly the blinking isn't solved in the latest build yet(?)

**Comment by sreilly** [comment]
@thm almost there... I think

**Comment by sreilly** [comment]
ok, done.  any stories that are removed from the current view will also now animate out nicely

**Comment by thm** [comment]
@sreilly This is really great!
